<?php
/**
 * Copyright © 2013-2017 Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php if (!$_productCollection->count()): ?>
    <div class="message info empty"><div><?php /* @escapeNotVerified */ echo __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getToolbarHtml() ?>
    <?php echo $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $image = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $image = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>
    <div class="products wrapper <?php /* @escapeNotVerified */ echo $viewMode; ?> products-<?php /* @escapeNotVerified */ echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <ol class="products list items product-items">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product): ?>
                 <?php
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                $obj_product = $objectManager->create('Magento\Catalog\Model\Product');
                $product = $obj_product->load($_product->getId());
                $productData = $product->getPreLoadedTemplate();
                $config = $objectManager->create('Magento\Framework\App\Config\ScopeConfigInterface');
                $layout = $config->getValue('productdesigner/selectview/Selectview');
                $product_images = $product->getAllMediaGalleryImages();
                $isByiEnable = 0;
                ?>
                <?php $isPdEnable = $this->helper('Biztech\Productdesigner\Helper\Info')->isPdEnable($_product->getId()); ?>
                 <?php if ($this->helper('Biztech\Productdesigner\Helper\Data')->isEnable()): ?>
                    <?php if (isset($isPdEnable) && $isPdEnable && count($product_images) > 0) : ?>
                        <?php if ($this->helper('Biztech\Productdesigner\Helper\Info')->checkDesignArea($_product->getId())) : ?>
                            <?php $isByiEnable = 1; ?>
                        <?php endif; ?>
                    <?php endif; ?>
                <?php endif; ?>


                <?php /* @escapeNotVerified */ echo($iterator++ == 1) ? '<li class="item product product-item">' : '</li><li class="item product product-item">' ?>
                <div class="product-item-info" data-container="product-grid">
                    <?php
                    $productImage = $block->getImage($_product, $image);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <?php if ($isByiEnable && $productData) :
                            $designImages = $objectManager->create('Biztech\Productdesigner\Model\Mysql4\Designtemplateimages\Collection')->addFieldToFilter('designtemplates_id',Array('eq' => $productData))->addFieldToFilter('design_image_type', 'base_high')->getFirstItem()->getData();
                            $imagePath = isset($designImages['image_path']) ? $designImages['image_path'] : '';
                        ?>
                            <a href="<?php if ($layout == 'box_view'): ?><?php echo $this->getUrl('productdesigner/index/index', array('_secure' => $this->getRequest()->isSecure(),'id' => $_product->getId(),'templateid' => $productData)); ?><?php else: ?><?php echo $this->getUrl('productdesigner/index/full', array('_secure' => $this->getRequest()->isSecure(),'id' => $_product->getId(),'templateid' => $productData)); ?><?php endif; ?>" class="product photo product-item-photo" tabindex="-1">
                                <?php if($imagePath) : ?>
                                    <?php if ($viewMode=='list'): ?>
                                        <span class="product-image-container" style="width:240px;">
                                        <span class="product-image-wrapper" style="padding-bottom: 125%;">
                                    <?php endif ?>
                                    <img src="<?php echo $this->helper('Magento\Catalog\Helper\Image')->init($product,
                                        'product_page_image')->setImageFile($designImages['image_path'])->resize(240,
                                        300)->keepAspectRatio(true)->constrainOnly(false)->getUrl();
                                        ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product,'small_image'),null,true) ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product,'small_image'),null,true)?>" />
                                <?php else : ?>
                                    <?php echo $productImage->toHtml(); ?>
                                <?php endif; ?>
                            </a>
                    <?php else : ?>
                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                        <?php echo $productImage->toHtml(); ?>
                    </a>
                    <?php endif; ?>
                    <div class="product details product-item-details">
                        <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>
                        <strong class="product name product-item-name">
                            <?php if ($isByiEnable && $productData) : ?>
                                <a class="product-item-link"
                                   href="<?php if ($layout == 'box_view'): ?><?php echo $this->getUrl('productdesigner/index/index', array('_secure' => $this->getRequest()->isSecure(),'id' => $_product->getId(),'templateid' => $productData)); ?><?php else: ?><?php echo $this->getUrl('productdesigner/index/full', array('_secure' => $this->getRequest()->isSecure(),'id' => $_product->getId(),'templateid' => $productData)); ?><?php endif; ?>" title="<?php echo $_productNameStripped; ?>">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                                </a>
                            <?php else : ?>
                            <a class="product-item-link"
                               href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>">
                                <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getName(), 'name'); ?>
                            </a>
                            <?php endif; ?>
                        </strong>
                        <!--Start Featured Attributes -->
                        <span class="text-center">
                        <?php
                        if ($this->helper('Magento\Catalog\Helper\Data')->isModuleOutputEnabled('Swissup_FeaturedAttributes')) {
                            echo $block->getLayout()
                                ->createBlock('Swissup\FeaturedAttributes\Block\Attributes')
                                ->setProduct($_product)
                                ->toHtml();
                        }
                        ?>
                        </span><!--End Featured Attributes -->

                        <?php echo $block->getReviewsSummaryHtml($_product, $templateType); ?>
                        <?php /* @escapeNotVerified */ echo $block->getProductPrice($_product) ?>
                        <?php echo $block->getProductDetailsHtml($_product); ?>



                        <div class="product-item-inner">
                            <div class="product actions product-item-actions"<?php echo strpos($pos, $viewMode . '-actions') ? $position : ''; ?>>
                                <div class="actions-primary"<?php echo strpos($pos, $viewMode . '-primary') ? $position : ''; ?>>
                                    <?php if ($isByiEnable && $productData) : ?>
                                        <?php if ($config->getValue('productdesigner/general/enabledesign')): ?>
                                        <button type="button" title="<?php echo __('Design It') ?>" class="button btn-cart list-design-button" onclick="<?php if ($layout == 'box_view'): ?>window.location.href = '<?php echo $this->getUrl('productdesigner/index/index', array('_secure' => $this->getRequest()->isSecure(),'id' => $_product->getId(),'templateid' => $productData)); ?>' <?php else: ?>window.location.href = '<?php echo $this->getUrl('productdesigner/index/full', array('_secure' => $this->getRequest()->isSecure(),'id' => $_product->getId(),'templateid' => $productData)); ?>'<?php endif; ?>"><span><span><?php echo __('Design It') ?></span></span></button>
                                            <?php endif; ?>
                                    <?php elseif($isByiEnable && !$productData): ?>
                                        <?php if ($config->getValue('productdesigner/general/enabledesign')): ?>
                                        <button type="button" title="<?php echo __('Design It') ?>" class="button btn-cart list-design-button" onclick="<?php if ($layout == 'box_view'): ?>window.location.href = '<?php echo $this->getUrl('productdesigner/index/index', array('_secure' => $this->getRequest()->isSecure(),'id' => $_product->getId())); ?>' <?php else: ?>window.location.href = '<?php echo $this->getUrl('productdesigner/index/full', array('_secure' => $this->getRequest()->isSecure(),'id' => $_product->getId())); ?>'<?php endif; ?>"><span><span><?php echo __('Design It') ?></span></span></button>
                                            <?php endif; ?>
                                    <?php endif; ?>
                                    <?php if ($_product->isSaleable()): ?>
                                        <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                        <?php if ($this->helper('Biztech\Productdesigner\Helper\Data')->isEnable()): ?>
                                            <?php if (isset($isPdEnable) && $isPdEnable) : ?>
                                                <?php if (!$config->getValue('productdesigner/general/enableaddtocart')): ?>
                                                    <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                        <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                        <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                        <?php echo $block->getBlockHtml('formkey')?>
                                                        <button type="submit"
                                                                title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                                class="action tocart primary">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                        </button>
                                                    </form>
                                                <?php endif; ?>
                                            <?php else : ?>
                                                <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                    <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                    <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                    <?php echo $block->getBlockHtml('formkey')?>
                                                    <!-- <button type="submit"
                                                            title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                            class="action tocart primary">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                    </button> -->
                                                </form>
                                            <?php endif; ?>
                                        <?php else : ?>
                                            <form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
                                                <input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
                                                <input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
                                                <?php echo $block->getBlockHtml('formkey')?>
                                                <button type="submit"
                                                        title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
                                                        class="action tocart primary">
                                                    <span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php endif; ?>
                                    <?php else: ?>
                                        <?php if ($_product->getIsSalable()): ?>
                                            <div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
                                        <?php else: ?>
                                            <div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
                                        <?php endif; ?>
                                    <?php endif; ?>
                                </div>
                                <div data-role="add-to-links" class="actions-secondary"<?php echo strpos($pos, $viewMode . '-secondary') ? $position : ''; ?>>
                                    <?php if ($addToBlock = $block->getChildBlock('addto')): ?>
                                        <?php echo $addToBlock->setProduct($_product)->getChildHtml(); ?>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <?php if ($showDescription):?>
                                <div class="product description product-item-description">
                                    <?php /* @escapeNotVerified */ echo $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                    <a href="<?php /* @escapeNotVerified */ echo $_product->getProductUrl() ?>" title="<?php /* @escapeNotVerified */ echo $_productNameStripped ?>"
                                       class="action more"><?php /* @escapeNotVerified */ echo __('Learn More') ?></a>
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                </div>
                <?php echo($iterator == count($_productCollection)+1) ? '</li>' : '' ?>
            <?php endforeach; ?>
        </ol>
    </div>
    <?php echo $block->getToolbarHtml() ?>
    <?php if (!$block->isRedirectToCartEnabled()) : ?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {}
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
