<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category  BSS
 * @package   Bss_ConfigurableProductWholesale
 * @author    Extension Team
 * @copyright Copyright (c) 2017-2018 BSS Commerce Co. ( http://bsscommerce.com )
 * @license   http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
    $product = $block->getSaleableItem();
    $helper = $this->helper('Bss\ConfigurableProductWholesale\Helper\Data');
    $priceModel = $block->getPriceType('regular_price');
    $idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
?>
<?php if (isset($product)) :?>
    <?php
        $minDataPrice = $helper->getRangePrice($product, true);
        $maxDataPrice = $helper->getRangePrice($product, false, true);
        $minPrice = $minDataPrice['finalPrice'];
        $maxPrice = $maxDataPrice['finalPrice'];
        $minExclTaxPrice = $minDataPrice['exclTaxFinalPrice'];
        $maxExclTaxPrice = $maxDataPrice['exclTaxFinalPrice'];
    ?>
    <?php if ($minPrice != $maxPrice) :?>
        <div class="bss-price-range">
            <span class="bss-price-from">
                <span class="bss-price-label">
                    <?php /* @noEscape */ echo __('From');?>
                </span>
                <span class="bss-price-from-value" data-price-amount="<?php /* @noEscape */ echo $minPrice;?>">
                    <?php /* @noEscape */ echo $helper->getFormatPrice($minPrice);?>
                </span>
            </span>
            <span class="bss-price-to">
                <span class="bss-price-label">
                    <?php /* @noEscape */ echo __('To');?>
                </span>
                <span class="bss-price-to-value" data-price-amount="<?php /* @noEscape */ echo $maxPrice;?>">
                    <?php /* @noEscape */ echo $helper->getFormatPrice($maxPrice);?>
                </span>
            </span>
            <?php if ($helper->getExclTaxConfig()) :?>
                <br />
                <span class="bss-price-label">
                    <?php /* @noEscape */ echo __('Excl. Tax:');?>
                </span>
                <span class="bss-excltax-price-from">
                    <span class="bss-price-label">
                        <?php /* @noEscape */ echo __('From');?>
                    </span>
                    <span class="bss-excltax-price-from-value" data-price-amount="<?php /* @noEscape */ echo $minExclTaxPrice;?>">
                        <?php /* @noEscape */ echo $helper->getFormatPrice($minExclTaxPrice);?>
                    </span>
                </span>
                    <span class="bss-excltax-price-to">
                    <span class="bss-price-label">
                        <?php /* @noEscape */ echo __('To');?>
                    </span>
                    <span class="bss-excltax-price-to-value" data-price-amount="<?php /* @noEscape */ echo $maxExclTaxPrice;?>">
                        <?php /* @noEscape */ echo $helper->getFormatPrice($maxExclTaxPrice);?>
                    </span>
                </span>
            <?php endif; ?>
        </div>
    <?php else :?>
        <span class="unit-price">
            <span class="bss-price-unit">
                <span class="bss-price-label">
                    <?php /* @noEscape */ echo __('Unit Price:'); ?>
                </span>
                <span class="bss-price-unit-value" data-price-amount="<?php /* @noEscape */ echo $minPrice;?>">
                    <?php /* @noEscape */ echo $helper->getFormatPrice($minPrice);?>
                </span>
            </span>
            <?php if ($helper->getExclTaxConfig()) :?>
                <br />
                <span class="bss-excltax-price-unit">
                    <span class="bss-price-label">
                        <?php /* @noEscape */ echo __('Excl. Tax:'); ?>
                    </span>
                    <span class="bss-excltax-price-unit-value" data-price-amount="<?php /* @noEscape */ echo $minExclTaxPrice;?>">
                        <?php /* @noEscape */ echo $helper->getFormatPrice($minExclTaxPrice);?>
                    </span>
                </span>
            <?php endif; ?>
        </span>
        </br>
        <?php if ($block->hasSpecialPrice()) :?>
            <span class="old-price">
                <?php /* @noEscape */ echo $block->renderAmount($priceModel->getAmount(), [
                    'display_label'     => __('Regular Price'),
                    'price_id'          => $block->getPriceId('old-price-' . $idSuffix),
                    'price_type'        => 'oldPrice',
                    'include_container' => true,
                    'skip_adjustments'  => true
                    ]); ?>
            </span>
        <?php endif; ?>
    <?php endif; ?>
<?php endif; ?>
