<?php
/**
 * @author    ThemePunch <info@themepunch.com>
 * @link      https://www.themepunch.com/
 * @copyright 2019 ThemePunch
 */

use \Nwdthemes\Revslider\Helper\Framework;
use \Nwdthemes\Revslider\Model\Revslider\Admin\Includes\RevSliderAddons;
use \Nwdthemes\Revslider\Model\Revslider\Admin\Includes\RevSliderFunctionsAdmin;
use \Nwdthemes\Revslider\Model\Revslider\Admin\Includes\RevSliderPluginUpdate;
use \Nwdthemes\Revslider\Model\Revslider\RevSliderSlider;
use \Nwdthemes\Revslider\Model\Revslider\RSColorpicker;

$frameworkHelper->reGeneratePluginPath();

$frameworkHelper->do_action('admin_enqueue_scripts', 'toplevel_page_revslider');

$rsaf	= new RevSliderFunctionsAdmin($frameworkHelper);
$rsa	= $rsaf->get_short_library();
$rsupd	= new RevSliderPluginUpdate($frameworkHelper);
$rsaddon= new RevSliderAddons($frameworkHelper);

$rs_addon_update		 = $rsaddon->check_addon_version();
$rs_addons				 = $rsaddon->get_addon_list();
$rs_wp_date_format		 = $frameworkHelper->get_option('date_format');
$rs_wp_time_format		 = $frameworkHelper->get_option('time_format');
$rs_added_image_sizes	 = $rsaf->get_all_image_sizes();
$rs_image_meta_todo		 = $frameworkHelper->get_option('rs_image_meta_todo', array());
$rs_slider_update_needed = $rsupd->slider_need_update_checks();
$rs_global_settings		 = $rsaf->get_global_settings();
$rs_global_sizes		 = array(
	'd' => $rsaf->get_val($rs_global_settings, array('size', 'desktop'), '1240'),
	'n' => $rsaf->get_val($rs_global_settings, array('size', 'notebook'), '1024'),
	't' => $rsaf->get_val($rs_global_settings, array('size', 'tablet'), '778'),
	'm' => $rsaf->get_val($rs_global_settings, array('size', 'mobile'), '480')
);
$rs_show_updated = $frameworkHelper->get_option('rs_cache_overlay', Framework::RS_REVISION);
if(version_compare(Framework::RS_REVISION, $rs_show_updated, '>')){
    $frameworkHelper->update_option('rs_cache_overlay', Framework::RS_REVISION);
}
$rs_notices = $rsaf->add_notices();
$rs_color_picker_presets = RSColorpicker::get_color_presets($frameworkHelper);

// Include registered styles
foreach ($frameworkHelper->getRegisteredStyles() as $_style) {
	echo '<link  rel="stylesheet" type="text/css"  media="all" href="' . $_style . '" />' . "\n";
}
?>
<!-- GLOBAL VARIABLES -->
<?php echo $frameworkHelper->getLocalizeScriptsHtml(); ?>
<script type="text/javascript">

	var RS_DO_SILENT_SLIDER_UPDATE,
		rs_do_silent_update,
		ajaxurl = "<?php echo $frameworkHelper->getBackendUrl('nwdthemes_revslider/revslider/ajax', ['isAjax' => 'true']); ?>",
		revMageImageUploadUrl = '<?php echo $frameworkHelper->getBackendUrl('nwdthemes_revslider/gallery/index', ['type'=>'file_type']); ?>',
		overviewUrl = '<?php echo $frameworkHelper->getBackendUrl('nwdthemes_revslider/revslider/overview'); ?>';

	define('wpColorPickerL10n', [], function() {
        return <?php echo json_encode(array(
            'clear' => __('Clear'),
            'defaultString' => __('Default'),
            'pick' => __('Select Color'),
            'current' => __('Current Color')
        )); ?>;
    });

	require(['jquery', 'admin'], function(jQuery, RVS) {

	window.RVS = window.RVS === undefined ? {F:{}, C:{}, ENV:{}, LIB:{}, V:{}, S:{}, DOC:jQuery(document), WIN:jQuery(window)} : window.RVS;

	RVS.LIB.ADDONS = RVS.LIB.ADDONS === undefined ? {} : RVS.LIB.ADDONS;
	RVS.LIB.ADDONS			= jQuery.extend(true,RVS.LIB.ADDONS,<?php echo (!empty($rs_addons)) ? 'jQuery.parseJSON('.$rsaf->json_encode_client_side($rs_addons).')' : '{}'; ?>);
	RVS.LIB.OBJ 			= {types: jQuery.parseJSON(<?php echo $rsaf->json_encode_client_side($rsa); ?>)};
	RVS.LIB.SLIDERS			= <?php echo json_encode(RevSliderSlider::get_sliders_short_list()); ?>;
	RVS.LIB.COLOR_PRESETS	= <?php echo (!empty($rs_color_picker_presets)) ? 'jQuery.parseJSON('. $rsaf->json_encode_client_side($rs_color_picker_presets) .')' : '{}'; ?>;

	RVS.ENV.addOns_to_update = <?php echo (!empty($rs_addon_update)) ? 'jQuery.parseJSON('.$rsaf->json_encode_client_side($rs_addon_update).');' : '{};'; ?>
	RVS.ENV.activated		= '<?php echo ($frameworkHelper->get_option('revslider-valid', 'false')) == 'true' ? 'true' : 'false'; ?>';
	RVS.ENV.activated = RVS.ENV.activated=='true'  || RVS.ENV.activated==true ? true : false;
	RVS.ENV.nonce			= '<?php echo $frameworkHelper->wp_create_nonce('revslider_actions'); ?>';
	RVS.ENV.plugin_dir		= 'revslider';
	RVS.ENV.slug_path		= '<?php echo Framework::RS_PLUGIN_SLUG_PATH; ?>';
	RVS.ENV.slug			= '<?php echo Framework::$RS_PLUGIN_SLUG; ?>';
	RVS.ENV.plugin_url		= '<?php echo Framework::$RS_PLUGIN_URL; ?>';
	RVS.ENV.wp_plugin_url 	= '<?php echo Framework::$WP_PLUGIN_URL . "/"; ?>';
	RVS.ENV.admin_url		= '<?php echo $frameworkHelper->getBackendUrl('nwdthemes_revslider/revslider/builder'); ?>';
	RVS.ENV.revision		= '<?php echo Framework::RS_REVISION; ?>';
	RVS.ENV.updated			= <?php echo (version_compare(Framework::RS_REVISION, $rs_show_updated, '>')) ? 'true' : 'false'; ?>;
	RVS.ENV.latest_version	= '<?php echo $frameworkHelper->get_option('revslider-latest-version', Framework::RS_REVISION); ?>';
	RVS.ENV.placeholder		= {
		date_format: '<?php echo $rs_wp_date_format; ?>',
		time_format: '<?php echo $rs_wp_time_format; ?>',
		date_today:	 '<?php echo date($rs_wp_date_format); ?>',
		time:		 '<?php echo date($rs_wp_time_format); ?>',
		tomorrow:	 '<?php echo date($rs_wp_date_format, strtotime(date($rs_wp_date_format) . ' +1 day')); ?>',
		last_week:	 '<?php echo date($rs_wp_date_format, strtotime(date($rs_wp_date_format) . ' -7 day')); ?>',
		date:				'<?php echo date($rs_wp_date_format); ?>',
		date_modified:		'<?php echo date($rs_wp_date_format); ?>'
	};
	RVS.ENV.glb_slizes		= jQuery.parseJSON(<?php echo $rsaf->json_encode_client_side($rs_global_sizes); ?>);
	RVS.ENV.img_sizes		= jQuery.parseJSON(<?php echo $rsaf->json_encode_client_side($rs_added_image_sizes); ?>);
	RVS.ENV.create_img_meta	= <?php echo (!empty($rs_image_meta_todo)) ? 'true' : 'false'; ?>;
	RVS.ENV.notices			= <?php echo (!empty($rs_notices)) ? 'jQuery.parseJSON('. $rsaf->json_encode_client_side($rs_notices) .')' : '[]'; ?>;
	<?php
	if($rs_slider_update_needed == true){
	?>
	RS_DO_SILENT_SLIDER_UPDATE = <?php echo ($rs_slider_update_needed == true) ? 'true' : 'false'; ?>;

	rs_do_silent_update = function() {
		RVS.F.ajaxRequest('silent_slider_update', {}, function(response){
			if(response.status !== 'finished'){
				rs_do_silent_update();
			}else{
				RS_DO_SILENT_SLIDER_UPDATE = false;
			}
		}, true);
	}

	if(RS_DO_SILENT_SLIDER_UPDATE === true){
		//push request to update slider for slider until finished
		jQuery(document).ready(function(){
			rs_do_silent_update();
		});
	}

	<?php
	}
	?>

	});
</script>
<?php
$frameworkHelper->do_action('revslider_header_content', $rsaf);
?>

<?php
//added for builder
?>
<script>
	require(['https://player.vimeo.com/api/player.js'], function(vimeoPlayer) {
		window['Vimeo'] = {Player: vimeoPlayer};
	});
</script>
<script src="https://www.youtube.com/iframe_api"></script>
<!-- COLLECTOR FOR ADDONS -->

<div id="wpbody">

<!-- WAIT A MINUTE OVERLAY CONTAINER -->
<div id="waitaminute">
	<div class="waitaminute-message"><i class="eg-icon-emo-coffee"></i><br><?php echo __('Please Wait...', 'revslider'); ?></div>
</div>

<!-- TOP RIGHT CORNER INFORMATION CONTAINER -->
<div id="rb_maininfo_wrap"></div>