<div class="slider-revolution-update-list">

	<h3 class="version-number">Version 6.1.1.3 (25th May 2020)</h3>
	<div class="change"><strong style="font-weight:700">CHANGES</strong></div>
    <ul>
        <li>Changed Add-On download url</li>
    </ul>
	<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
	<ul>
        <li>Added missing minified font styles</li>
        <li>Added missing Store Visibility feature to slides</li>
    </ul>

	<h3 class="version-number">Version 6.1.1.2 (21th May 2020)</h3>
	<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
    <ul>
        <li>Fixed svg path error</li>
        <li>Fixed slider editor error in js bundle mode</li>
    </ul>

	<h3 class="version-number">Version 6.1.1.1 (20th May 2020)</h3>
	<div class="bugfix"><strong style="font-weight:700">BUGFIXES</strong></div>
    <ul>
        <li>Fixed get animations error</li>
    </ul>

	<h3 class="version-number">Version 6.1.1 (9th May 2020)</h3>
	<div class="newfeature"><strong style="font-weight:700">A New Content Building Standard.</strong></div>
	<ul>
		<li>The world's most powerful WordPress builder with advanced animations now on Magento 2</li>
		<li>Create outstanding, professional content modules with no coding experience required</li>
		<li>50+ new features</li>
		<li>Sliders & Carousels, Hero Headers, Content Blocks and Modules, Full Websites, Dynamic Solutions, Special FX</li>
		<li>Run any Slider Revolution module as a modal popup</li>
	</ul>
	<div class="newfeature"><strong style="font-weight:700">The Visual Editor you want to work with.</strong></div>
	<ul>
		<li>Better usability</li>
		<li>Work faster & more efficiently</li>
		<li>Eye friendly dark user interface</li>
		<li>Improved loading times</li>
	</ul>
	<div class="newfeature"><strong style="font-weight:700">The animators dream. Now with keyframes.</strong></div>
	<ul>
		<li>Easy to understand structure</li>
		<li>In-depth animation settings</li>
		<li>New easing types</li>
		<li>Animation presets</li>
		<li>Loop the whole timeline or between individual keyframes</li>
		<li>Scroll-based timeline animations</li>
	</ul>
	<div class="newfeature"><strong style="font-weight:700">Mighty new content. Pure inspiration.</strong></div>
	<ul>
		<li>Many new templates</li>
		<li>New images, videos, icons, etc.</li>
		<li>Animated layer groups</li>
		<li>Quickstyle layer presets</li>
	</ul>
	<div class="newfeature"><strong style="font-weight:700">Live help within the editor</strong></div>
	<ul>
		<li>Explanation for any option</li>
		<li>Search & highlight options</li>
		<li>Documentation & FAQ links</li>
	</ul>
	<div class="newfeature"><strong style="font-weight:700">200+ ready to go templates</strong></div>
	<ul>
		<li>19 new templates added in 6.0</li>
		<li>The right template for every occasion</li>
		<li>From simple headers to full websites</li>
		<li>Special FX templates with add-ons</li>
	</ul>

</div>