<?php 
$product_id = $this->getRequest()->getParam('id');

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$obj_product = $objectManager->create('Magento\Catalog\Model\Product');
$product = $obj_product->load($product_id);
$storeManager = $objectManager->get('Magento\Store\Model\StoreManagerInterface');
$storeid = $storeManager->getStore()->getId();
$default_color = $this->helper('Biztech\Productdesigner\Helper\Info')->getDefaultImage($product_id);

$customOptions = !empty($this->getRequest()->getParam('customoption')) ? $this->getRequest()->getParam('customoption') : '';
$customOptionsArray = isset($customOptions) ?  json_decode(base64_decode($customOptions),true) : '';
?>
<div id = "custom-option">
    <?php 
    $dynamicOptions = $objectManager->get(\Itoris\DynamicProductOptions\Block\Options\Config::class);
    echo $dynamicOptions->setTemplate('Biztech_Productdesigner::productdesigner/products/itoris_customOptions.phtml')
                // ->setDynamicOptionClass($dynamicOptions)
    ->toHtml();
    $allFieldsJson = $dynamicOptions->getAllFieldsJson();
    $allFieldsJson1 = json_decode($allFieldsJson,true);
    // print_r(get_class_methods($dynamicOptions));
    ?>
</div>
<!-- <form name="customOptionFormProdSettings" id="customOptionFormProdSettings" data-mage-init='{"validation":{}}' onsubmit="return false" method="POST" > -->
    <input type="hidden" name="product" value="<?= $product_id ?>">
    <form action="" method="post" id="product_addtocart_form" enctype="multipart/form-data">
        <h2 class=" product-name customoptions-heading"><?php echo __('Product Custom Options'); ?></h2>
        <!-- <a href="<?php echo $product->getProductUrl(); ?>">Product URL</a> -->
        <?php $blockObj= $block->getLayout()->createBlock('\Magento\Catalog\Block\Product\View\Options'); ?>
                       
        <div class="product-options-wrapper" id="product-options-wrapper" data-hasrequired="* Required Fields">
            <div class="fieldset" tabindex="0">
                <script type="text/x-magento-init">
                    {
                        "#product_addtocart_form": {
                            "priceOptions": {
                                "optionConfig": <?php /* @escapeNotVerified */ echo $blockObj->getJsonConfig()?>,
                                "controlContainer": ".field",
                                "priceHolderSelector": "[data-product-id='<?php echo $blockObj->escapeHtml($product_id)?>'][data-role=priceBox]"
                            }
                        }
                    }
                </script>
        <?php 
/*
$layout = $block->getLayout();
$block_header = $layout->createBlock('Magento\Catalog\Block\Product\View\Options')
->setTemplate('Magento_Catalog::product/view/options.phtml');

$block_links1  = $layout->createBlock('Magento\Catalog\Block\Product\View\Options\Type\DefaultType','default')->setTemplate('Magento_Catalog::product/view/options/type/default.phtml');
$block_header->setChild('default',$block_links1);

$block_links2  = $layout->createBlock('Magento\Catalog\Block\Product\View\Options\Type\Text','text')->setTemplate('Magento_Catalog::product/view/options/type/text.phtml');
$block_header->setChild('text',$block_links2);

$block_links3  = $layout->createBlock('Magento\Catalog\Block\Product\View\Options\Type\File','file')->setTemplate('Magento_Catalog::product/view/options/type/file.phtml');
$block_header->setChild('file',$block_links3);
$block_links4  = $layout->createBlock('Magento\Catalog\Block\Product\View\Options\Type\Select','select')->setTemplate('Magento_Catalog::product/view/options/type/select.phtml');
$_option = $block->getOption();
$class = ($_option->getIsRequire()) ? ' required' : '';
*/
/*$block_links5  = $layout->createBlock('Magento\Catalog\Block\Product\View\Options\Type\Date','date')->setTemplate('Magento_Catalog::product/view/options/type/date.phtml');
$block_header->setChild('date',$block_links5);
echo $block_header->toHtml();
*/
?>
        <!-- <div id = "custom-option"> -->
            <?php
            $all_options = $product->getOptions();
            if (empty($all_options)) { ?>
                    <span class="no-customoptions"><?php echo __('There are no options available for this product.'); ?></span>
                <?php
            } else if ($all_options) {
                $dropcnt = 0;
                $newcount = 2;

                foreach ($all_options as $option) {
                   /* if ($option->getDefaultTitle() == 'Online Imprint Proof') {
                        continue;
                    }*/
                    $optionType = $option->getType();
                    if ($optionType == 'multiple') {

                        ?>
                <div class="field <?php if ($option->getIsRequire() == 1) { ?> required <?php } ?>">
                <label class="label" for="select_<?= $option->getOptionId() ?>">
                    <span><?php echo $option->getDefaultTitle(); ?></span>
                </label>
                <div class="control">   
                    <?php //print_r($option->getData()); ?>
                    <select multiple="multiple" id="select_<?= $option->getOptionId() ?>" class="multiselect admin__control-multiselect product-custom-option <?php if ($option->getIsRequire() == 1) { ?> required <?php } ?>" name="options[<?php echo $option->getOptionId(); ?>]" data-selector="options[<?php echo $option->getOptionId(); ?>]" aria-required="true">
                        <?php
                        foreach ($option->getValues() as $value) :

                            if ($value->getPriceType() == 'fixed') {
                                $price = $value->getDefaultPrice();
                            } else {
                                $price = ($value->getDefaultPrice() * $product->getFinalPrice() / 100);
                            }
                            $price1 = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($price, true, false);
                            ?>
                            <option value="<?php echo $value->getOptionTypeId(); ?>" data-price="<?= $price ?>"
                                <?php 
                                if (!empty($customOptionsArray)) {
                                    foreach ($customOptionsArray as $customOptions) {
                                        if ($value->getOptionTypeId() == $customOptions['value']) {
                                            echo 'selected="selected"';
                                        }
                                    }} ?>
                                    >
                                    <?php echo $value->getDefaultTitle() . ' + ' . $price1; ?>
                                </option>  
                            <?php endforeach; ?>
                        </select>
                    </div>                                   
                </div>
                            <?php
                        } else if ($optionType == 'drop_down') {
                            $values = $option->getValues();
                            ?>  
<div class="field <?php if ($option->getIsRequire() == 1) { ?> required <?php } ?>">
    <label class="label" for="select_<?= $option->getOptionId() ?>">
        <span><?php echo $option->getDefaultTitle(); ?></span>
    </label>
    <div class="control">    
        <?php 
            $designerColor = '';
           /* foreach ($allFieldsJson1 as $allFieldsJsons) {
                if (isset($allFieldsJsons['items'])) {
                    foreach ($allFieldsJsons['items'] as $value) {
                        if ($value['option_id'] == $option->getOptionId()) {
                            if (isset($value['use_productdesginer'])) {
                                if ($value['use_productdesginer'] == 1) {
                                    $designerColor= 'designer-printing-color';
                                }
                            }
                        }
                    }
                }                
            }            */
            if ($product->getDesignerImprintOption()) {
                if ($product->getDesignerImprintOption() == $option->getOptionId()) {
                    $designerColor= 'designer-printing-color';
                }
            }
         ?>
        <select name="options[<?php echo $option->getOptionId(); ?>]" data-selector="options[<?php echo $option->getOptionId(); ?>]" id="select_<?= $option->getId()?>" class="<?= $designerColor ?><?php if ($option->getIsRequire() == 1) { ?> required <?php } ?> product-custom-option admin__control-select"  title="Choose your option" aria-required="true">
                                    <option value="">--- Please Select ---</option>
                                    <?php
                                    foreach ($option->getValues() as $value) :

                                        if ($value->getPriceType() == 'fixed') {
                                            $price = $value->getDefaultPrice();
                                        } else {
                                            $price = ($value->getDefaultPrice() * $product->getFinalPrice() / 100);
                                        }
                                        ?>
<option data-title='<?= $value->getDefaultTitle(); ?>' value="<?php echo $value->getOptionTypeId(); ?>" data-price="<?= $price ?>"
<?php 
$price = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($price, true, false);
if (!empty($customOptionsArray)) {
foreach ($customOptionsArray as $customOptions) {
    if ($value->getOptionTypeId() == $customOptions['value']) {
        echo 'selected="selected"';
    }
}}
 ?>><?php echo $value->getDefaultTitle(); ?></option>  
                                        <?php endforeach; ?>
                                    </select>       
                                </div>
                            </div>
                            <?php
                        } else if ($optionType == 'checkbox') {
                            $values = $option->getValues();
                            $count = 2;
                            ?>  
<div class="field <?php if ($option->getIsRequire() == 1) { ?> required <?php } ?>">
    <label class="label" for="select_<?= $option->getOptionId() ?>">
        <span><?php echo $option->getDefaultTitle(); ?></span>
    </label>
    <div class="control">
        <div class="options-list nested" id="options-<?= $option->getOptionId() ?>-list">
                <?php
                foreach ($option->getValues() as $value) :
                    if ($value->getPriceType() == 'fixed') {
                        $price = $value->getDefaultPrice();
                    } else {
                        $price = ($value->getDefaultPrice() * $product->getFinalPrice() / 100);
                    }
                    ?>
                    <div class="field choice admin__field admin__field-option">
                        <input type="checkbox"
                            class="checkbox admin__control-checkbox <?php if ($option->getIsRequire() == 1) { ?> required <?php } ?> product-custom-option" 
                            name="options[<?php echo $option->getOptionId(); ?>][]" 
                            id="options_<?php echo $option->getOptionId(); ?>_<?php echo $count; ?>" 
                            value="<?= $value->getOptionTypeId() ?>" 
                            data-selector="options[<?php echo $option->getOptionId(); ?>][<?= $value->getOptionTypeId() ?>]"  
                            data-price="<?= number_format($price,2) ?>"
                        <?php 
                        $priceCheckbox = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($price, true, false);
                        if (!empty($customOptionsArray)) {
                            foreach ($customOptionsArray as $customOptions) {
                                if ($value->getOptionTypeId() == $customOptions['value']) {
                                    echo 'checked';
                                }
                            }
                        } ?>
                            >            
                            <label class="label admin__field-label" for="options_<?php echo $option->getOptionId(); ?>_<?php echo $count; ?>">
                                <?php if ($price > 0) {?>
                                <span><?php echo $value->getDefaultTitle() . '+ ' . $priceCheckbox; ?></span>
                                <?php } else{ ?>
                                <span><?php echo $value->getDefaultTitle(); ?></span>
                                <?php } ?>
                            </label>
                        </div>
                        <?php
                        $count = $count+1;
                    endforeach;
                    ?>
                </div>            
            </div>
        </div>                    
                            <?php } else if ($optionType == 'radio') {
                                $values = $option->getValues();
                                $count = 1;
                                ?>  

<div class="field <?php if ($option->getIsRequire() == 1) { ?> required <?php } ?>">
<label class="label" for="select_<?= $option->getOptionId() ?>">
    <span><?php echo $option->getDefaultTitle(); ?></span>
</label>
<div class="control">
    <div class="options-list nested" id="options-<?= $option->getOptionId() ?>-list">
           <?php
        foreach ($option->getValues() as $value) :
            if ($value->getPriceType() == 'fixed') {
                $price = $value->getDefaultPrice();
            } else {
                $price = ($value->getDefaultPrice() * $product->getFinalPrice() / 100);
            }
            ?>
                <div class="field choice admin__field admin__field-option">
                    <input type="radio" value="<?= $value->getOptionTypeId() ?>" id="options_<?php echo $option->getOptionId(); ?>_<?php echo $count; ?>" name="options[<?php echo $option->getOptionId(); ?>]" data-selector="options[<?php echo $option->getOptionId(); ?>]"  class="field choice admin__field admin__field-option  <?php if ($option->getIsRequire() == 1) { ?> required <?php } ?> product-custom-option" data-price="<?= $price ?>" aria-required="true"
                    <?php 
                    $priceRadio = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($price, true, false);
                    if (!empty($customOptionsArray)) {
                        foreach ($customOptionsArray as $customOptions) {
                            if ($value->getOptionTypeId() == $customOptions['value']) {
                                echo 'checked';
                            }
                        }} ?>
                        >            
                        <label class="label admin__field-label" for="options_<?php echo $option->getOptionId(); ?>_<?php echo $count; ?>">
                            <?php if ($price > 0) {?>
                            <span><?php echo $value->getDefaultTitle() . '+ ' . $priceRadio; ?></span>
                            <?php } else{ ?>
                            <span><?php echo $value->getDefaultTitle(); ?></span>
                            <?php } ?>
                        </label>
                    </div>
                <?php
                $count = $count+1;
            endforeach;
            ?>
    </div>                                    
    <span id="options-<?= $option->getOptionId() ?>-container"></span>
</div>
</div>
                                    <?php
                                }  else if ($optionType == 'area' || $optionType == 'field') {
    if ($option->getPriceType() == 'fixed') {
        $price = $option->getDefaultPrice();
    } else {
        $price = ($option->getDefaultPrice() * $product->getFinalPrice() / 100);
    }
    $price1 = $this->helper('Magento\Framework\Pricing\Helper\Data')->currency($price, true, false);
    ?>  

<div class="field <?php if ($option->getIsRequire() == 1) { ?> required <?php } ?>">
<label class="label" for="select_<?= $option->getOptionId() ?>">
     <?php if ($price > 0) {?>
    <span><?php echo $value->getDefaultTitle() . '+ ' . $price1; ?></span>
    <?php } else{ ?>
    <span><?php echo $value->getDefaultTitle(); ?></span>
    <?php } ?>
</label>
<div class="control">            
        <?php 
        $inputCustomOptionValue = '';
        if (!empty($customOptionsArray)) {
        foreach ($customOptionsArray as $customOptions) {
        if ('options['.$option->getOptionId().']' == $customOptions['name']) {
        $inputCustomOptionValue =  $customOptions['value'];
        }
        }} ?>                                    
        <input type="text" data-price="<?php echo $price; ?>" value="<?php echo $inputCustomOptionValue; ?>" name="options[<?php echo $option->getOptionId(); ?>]" data-selector="options[<?php echo $option->getOptionId(); ?>]" class="input-text required-entry product-custom-option " id="options_<?php echo $option->getOptionId(); ?>_text" <?php if ($option->getIsRequire() == 1) { ?>  data-validate="{required:true}"<?php } ?>>
    </div>
</div>
<?php } else if ($optionType == 'date' || $optionType == 'date_time' || $optionType == 'time') {
                                        ?>
                                        <div class="field date required">
                                            <fieldset class="fieldset fieldset-product-options-inner required">
                                                <label class="required"><?php echo $option->getDefaultTitle() . '+ ' . $option->getDefaultPrice(); ?></label> 
                                                <div class="control">
                                                    <?php if ($option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_DATE_TIME || $option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_DATE):
                                                    ?>

                                                    <?php echo $block->getDateHtml() ?>

                                                <?php endif; ?>
                                                <?php if ($option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_DATE_TIME || $option->getType() == \Magento\Catalog\Model\Product\Option::OPTION_TYPE_TIME):
                                                ?>
                                                <span class="time-picker"><?php echo $block->getTimeHtml() ?></span>
                                            <?php endif; ?>
                                            <?php if ($option->getIsRequire()): ?>
                                                <input type="hidden"
                                                name="validate_datetime_<?php /* @escapeNotVerified */ echo $option->getOptionId() ?>"
                                                class="validate-datetime-<?php /* @escapeNotVerified */ echo $option->getOptionId() ?>"
                                                value=""
                                                data-validate="{'validate-required-datetime':<?php /* @escapeNotVerified */ echo $option->getOptionId() ?>}"/>
                                            <?php else: ?>
                                                <input type="hidden"
                                                name="validate_datetime_<?php /* @escapeNotVerified */ echo $option->getOptionId() ?>"
                                                class="validate-datetime-<?php /* @escapeNotVerified */ echo $option->getOptionId() ?>"
                                                value=""
                                                data-validate="{'validate-optional-datetime':<?php /* @escapeNotVerified */ echo $option->getOptionId() ?>}"/>
                                            <?php endif; ?>
                                            <script type="text/x-magento-init">
                                                {
                                                    "#customOptionFormProdSettings": {
                                                    "validation": {
                                                    "ignore": ":hidden:not(input[name^='validate_datetime_'])"
                                                }
                                            }
                                        }
                                    </script>
                                </div>
                            </fieldset>
                        </div>
                        <?php
                    }
                    $newcount = $newcount + 1;
                }
            }
            ?>
            <!-- </div> -->
        </div>
    </div>
    <!-- this is required -->
    <div class="product-options-bottom" style="display: none;">
    <div class="box-tocart">
        <div class="fieldset">
            <div class="field qty">
                <label class="label" for="qty"></label>
                <div class="control"></div>
            </div>
            <div class="actions">
                <button type="submit" title="Add to Cart" class="action primary tocart" id="product-addtocart-button">
                    <span></span>
                </button>
            </div>
        </div>
    </div>
    <div class="product-info-price">
        <div class="product-info-stock-sku">
            <div class="stock available" title="Availability">
                <span></span>
            </div>
            <div class="product attribute sku">
                <strong class="type"></strong>    <div class="value" itemprop="sku"></div>
            </div>
        </div>
    </div>
    <!-- this is required -->
    <script>
        require([
            'jquery',
            'mage/mage',
            'Magento_Catalog/product/view/validation',
            'Magento_Catalog/js/catalog-add-to-cart'
            ], function ($) {
                'use strict';

                $('#product_addtocart_form').mage('validation', {
                    radioCheckboxClosest: '.nested',
                    submitHandler: function (form) {
                        var widget = $(form).catalogAddToCart({
                            bindSubmit: false
                        });

                        widget.catalogAddToCart('submitForm', $(form));

                        return false;
                    }
                });
            });
        </script>
    </div>
</form>
 
<?php $_product = $blockObj->getProduct(); ?>
<script>
    require([
        'jquery',
        'priceBox'
    ], function($){
        var dataPriceBoxSelector = '[data-role=priceBox]',
            dataProductIdSelector = '[data-product-id=<?php echo $blockObj->escapeHtml($_product->getId())?>]',
            priceBoxes = $(dataPriceBoxSelector + dataProductIdSelector);

        priceBoxes = priceBoxes.filter(function(index, elem){
            return !$(elem).find('.price-from').length;
        });

        priceBoxes.priceBox({'priceConfig': <?php /* @escapeNotVerified */ echo $blockObj->getJsonConfig() ?>});
    });
</script>
