<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2017 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php
/**
 * @see \Blackbird\ContentManager\Block\Adminhtml\ContentType\Edit\Tab\Layout\Configure
 */
?>

<div id="admin__field field field-layout_configure layout-configure" data-ui-id="contentmanager-contenttype-edit-form-fieldset-element-form-field-layout-configure">
    <div id="contenttype-layout-grid"></div>
</div>
