<?php  
    $cat_id = $this->getCatId();
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $quotes = $objectManager->create('Biztech\Productdesigner\Model\Mysql4\Quotes\Collection')->addFieldToFilter('status',array('eq'=>1));
    
    if(!$cat_id)
    {
        $cat_id = $block->getDefaultQuotesCategory();
    }
    $model = $objectManager->create('Biztech\Productdesigner\Model\Mysql4\Quotescategory\Collection')->addFieldToFilter('parent_categories',array('eq'=>$cat_id))->addFieldToFilter('status',array('eq'=>1));
    $quote_col = $model->getData();
    $quoteIds = array();
    foreach($quote_col as $quotec){
        $quoteIds[] = $quotec['quotescategory_id'];
    }
    $sub_cat_id = implode(',', $quoteIds);
?>
<?php if($cat_id): ?>
    <?php 
    if($sub_cat_id){
        $Cats = array();
        foreach(explode(',',$sub_cat_id) as $subCats){
            $Cats[] = $subCats;
        }
        $Cats[] = $cat_id;
        $quotes = $quotes->addFieldToFilter('category_id', array('in' => $Cats));
    }
    else{
        $quotes = $quotes->addFieldToFilter("category_id",array("eq"=>$cat_id));  
    }
endif; ?>

<ul id="quotes_list" class="quotes_list">
    <?php foreach($quotes as $quote): ?>        
        <span class="quote-text" data-text="<?php echo $quote->getQuotesText();?>"><?php echo $quote->getQuotesText();?></span>
    <?php endforeach; ?>
<?php if(count($quotes) == 0): ?>
    <li class="note-message"> <span class="a-center"> <?php echo __("Sorry, no quotes found"); ?>.</span></li>
<?php endif; ?>
</ul>