<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\Shopby\Block\Navigation\JsInit $block */
?>
<div data-am-js="js-init">
<script type="text/x-magento-init">
    {
        "[data-am-js='filter-item-default']": {
            "amShopbyFilterItemDefault": {
                "collectFilters": <?= /* @escapeNotVerified */ $block->collectFilters(); ?>
            }
        }
    }
</script>
</div>
