<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\Shopby\Block\Navigation\FilterRenderer\Category $block */
/** @var \Amasty\Shopby\Model\Layer\Filter\CategoryItems $filterItems */
/** @var \Amasty\Shopby\Model\Layer\Filter\Item $filterItem */
$filterItems = $block->getFilter()->getItems();
?>
<?php foreach ($filterItems->getItems($block->getPath()) as $filterItem) : ?>
    <?php $uniqId = uniqid(); ?>
    <?php $currentPath = ($block->getPath() ?: $filterItems->getStartPath()) . '/' . $filterItem->getValueString(); ?>
    <li class="item" data-label="<?= $block->escapeHtml($filterItem->getOptionLabel()) ?>">
        <?php if ($filterItems->getItemsCount($currentPath)) : ?>
            <span class="am-collapse-icon"></span>
        <?php endif; ?>

        <?php if ($filterItem->getCount()) : ?>
            <a class="am-filter-item-<?= $block->escapeId($uniqId) ?>
               <?php if ($block->getFilter()->getItemsCount($currentPath)) : ?>
                    <?= "amshopby-filter-parent"; ?>
               <?php endif; ?>"
               data-am-js="filter-item-default"
               href="<?= $block->escapeUrl($filterItem->getUrl()) ?>"
               <?= $filterItem->getRelNofollow() ? ' rel="nofollow"' : '' ?>>
                <input
                        name="amshopby[<?= /* @escapeNotVerified */
                        $block->getFilter()->getRequestVar(); ?>][]"
                        value="<?= $block->escapeHtml($filterItem->getValueString()); ?>"
                        type="<?= $block->getInputType(); ?>"
                    <?=  /* @escapeNotVerified */ $block->checkedFilter($filterItem) ? ' checked' : ''; ?>
                />
                <?= $filterItem->getOptionLabel() ?>
                <?php if ($block->getFilterSetting()->isShowProductQuantities()) : ?>
                    <span class="count"><?= $filterItem->getCount() ?>
                        <span class="filter-count-label">
                            <?php $title = ($filterItem->getCount() == 1) ? __('item') : __('items');?>
                            <?= $block->escapeHtml($title) ?>
                        </span>
                    </span>
                <?php endif; ?>
            </a>
        <?php else : ?>
            <?= $filterItem->getOptionLabel() ?>
            <?php if ($block->getFilterSetting()->isShowProductQuantities()) : ?>
                <span class="count"><?= $filterItem->getCount() ?>
                    <span class="filter-count-label">
                         <?php $title = ($filterItem->getCount() == 1) ? __('item') : __('items');?>
                         <?= $block->escapeHtml($title) ?>
                        </span>
                    </span>
            <?php endif; ?>
        <?php endif; ?>
        <?php if ($filterItems->getItemsCount($currentPath)): ?>
            <ol class="items items-children -folding level-<?= $block->getLevel(); ?>">
                <?= $block->renderChildrenItems($currentPath); ?>
            </ol>
        <?php endif; ?>
    </li>
<?php endforeach; ?>
