<?php
/**
 * ITORIS
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the ITORIS's Magento Extensions License Agreement
 * which is available through the world-wide-web at this URL:
 * http://www.itoris.com/magento-extensions-license.html
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to sales@itoris.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade the extensions to newer
 * versions in the future. If you wish to customize the extension for your
 * needs please refer to the license agreement or contact sales@itoris.com for more information.
 *
 * @category   ITORIS
 * @package    ITORIS_M2_PRODUCT_TABS
 * @copyright  Copyright (c) 2016 ITORIS INC. (http://www.itoris.com)
 * @license    http://www.itoris.com/magento-extensions-license.html  Commercial License
 */

namespace Itoris\Producttabsslider\Block\Frontend;

class BlockInfo extends \Magento\Catalog\Block\Product\View\Attributes
{
    const CACHE_TAG = 'info_product_tabs';
    protected $objectManager;
    protected $parseText;
    protected $_isScopePrivate=true;
    protected $_template = 'Itoris_Producttabsslider::product/tabs.phtml';
    public  function factoryBlockCms(){
            $this->objectManager=\Magento\Framework\App\ObjectManager::getInstance();
    }
    public function toHtml()
    {
        //if (!trim($this->getParseText())) return '';
        return parent::toHtml(); // TODO: Change the autogenerated stub
    }
    public function setParseText($parseText){
        $this->parseText=$parseText;
    }
    public function getParseText(){
        return  $this->parseText;
    }
}