<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_InfiniteScroll
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php /** @var $block \Magento\Catalog\Block\Product\Image */ ?>
<span class="product-image-container"
      style="width:<?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getWidth())?>px;">
    <span class="product-image-wrapper"
          style="padding-bottom: <?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getRatio() * 100); ?>%;background: #fff url('<?php echo $block->escapeHtml($block->getViewFileUrl("Bss_InfiniteScroll::images/loader.gif")); ?>') no-repeat 50% 50%">
        <img class="product-image-photo lazy"
            style="visibility: hidden;"
                <?= /* @escapeNotVerified */ $block->getCustomAttributes(); ?>
             src=""
             data-original="<?= /* @escapeNotVerified */ $block->getImageUrl(); ?>"
             max-width="<?= /* @escapeNotVerified */ $block->getWidth() ?>"
             max-height="<?= /* @escapeNotVerified */ $block->getHeight() ?>"
             alt="<?= /* @escapeNotVerified */ $block->stripTags($block->getLabel(), null, true); ?>"/></span>
</span>
