<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_ShopbyPage
 */
?>
<?php
/** @var $block \Amasty\ShopbyPage\Block\Adminhtml\Page\Selection */
?>
<script>
    require([
        'Amasty_ShopbyPage/js/selection'
    ], function (selection) {
        selection.init('<?=
            /* @escapeNotVerified */ $block->getSelectionUrl()
        ?>', '<?=
            /* @escapeNotVerified */ $block->getAddSelectionUrl()
        ?>', '<?=
            /* @escapeNotVerified */ $block->getCounter()
        ?>')
        window.amastyShopbyPageSelection = selection;
    })

</script>
