<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php /** @var \Amasty\Shopby\Block\Navigation\ApplyButton $block */?>
<?php $_postfix = uniqid();?>
<?php if ($block->blockEnabled()) :?>
    <?php if (!$block->isAjaxEnabled()) :?>
    <form data-amshopby-filter="">
        <input type="hidden"
               name="<?= /* @escapeNotVerified */ \Amasty\Shopby\Block\Navigation\UrlModifier::VAR_REPLACE_URL?>"
               value="1"/>
    </form>
    <?php endif;?>
    <div class="am_shopby_apply_filters">
        <div class="am-show-button -horizontal">
            <span class="am-items"></span>
            <button amshopby-apply-filter="1"
                    id="amasty_shopby_apply_filters_<?= /* @escapeNotVerified */ $_postfix;?>"
                    title="<?= $block->escapeHtml(__('Apply Filters')) ?>"
                    class="am-button">
                <?= $block->escapeHtml(__('Show'))?>
            </button>
        </div>

    </div>

    <script>
    require([
        'jquery',
        'amShopbyApplyFilters'
    ], function ($) {
        //<![CDATA[
            $('#amasty_shopby_apply_filters_<?= /* @escapeNotVerified */ $_postfix;?>').amShopbyApplyFilters({
                "ajaxEnabled": <?= /* @escapeNotVerified */ ($block->isAjaxEnabled() ? '1' : '0')?>,
                "navigationSelector": "<?= /* @escapeNotVerified */ $block->getNavigationSelector();?>",
                "clearUrl": "<?= /* @escapeNotVerified */ $block->getClearUrl();?>",
                "buttonPosition": "<?= /* @escapeNotVerified */ $block->getButtonPosition();?>"
            });
        //]]>
    });
    </script>
<?php endif;?>
