<?php
/**
 * @copyright: Copyright © 2017 Firebear Studio. All rights reserved.
 * @author   : Firebear Studio <fbeardev@gmail.com>
 */
?>
<div id="messages"><div class="messages">
        <div class="message message-notice"><div>
               <?php
               echo __(
                       "You have installed and enabled FireBear Studio Improved Import / Export extension - to use it please go to System -> %1 / %2. We don't improve and not make any changes on default Magento 2 Import / Export behaviour!",
                       "<a href=" . $this->url->getUrl('import/job/index') . ">Import Jobs</a>",
                "<a href=" . $this->url->getUrl('import/export_job/index') . ">Export Jobs</a>"
                ); ?>
            </div></div>
    </div>
</div>
