<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<?php
/**
 * Customer login form template
 *
 * @see \Magento\Customer\Block\Form\Login
 * @var $block \Magento\Customer\Block\Form\Login
 */
?>
<div class="block block-customer-login" style="display: none;" id="customer-login-container">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?php /* @escapeNotVerified */ echo __('Registered Customers') ?></strong>
    </div>

    <ul class="messages">
        <li id="login-error-msg" class="error-msg" style="color:red;font-size:large">          
        </li>
    </ul>
    <div class="block-content" aria-labelledby="block-customer-login-heading">

        <form class="form form-login"
              action="<?php /* @escapeNotVerified */ echo $block->getPostActionUrl() ?>"
              method="post"
              id="login-form-pd"
              onsubmit="return false"
              data-mage-init='{"validation":{}}'>
                  <?php echo $block->getBlockHtml('formkey'); ?>

            <fieldset class="fieldset login" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
                <div class="field note"><?php /* @escapeNotVerified */ echo __('If you have an account, sign in with your email address.') ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
                    <div class="control">

                        <input name="login[username]" value="<?php echo $block->escapeHtml($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" data-validate="{required:true, 'validate-email':true}">

                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?php /* @escapeNotVerified */ echo __('Password') ?></span></label>
                    <div class="control">

                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?php /* @escapeNotVerified */ echo __('Password') ?>" data-validate="{required:true, 'validate-password':true}">

                    </div>
                </div>
                <?php echo $block->getChildHtml('form_additional_info'); ?>
                <div class="actions-toolbar">

                    <div class="primary"><button type="submit" class="pd-button" id="customer-login-btn"><span><?php /* @escapeNotVerified */ echo __('Login') ?></span></button></div>

                    <div class="secondary">
                        <button class="pd-button" title="<?php /* @escapeNotVerified */ echo __('Create an Account') ?>" id="customer-register-btn" type="button"><span><span><?php /* @escapeNotVerified */ echo __('Create an Account') ?></span></span></button>
                    </div>
                </div>
            </fieldset>
        </form>
    </div>
</div>
