<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_ShopbyPage
 */
?>
<?php
/** @var $block \Amasty\ShopbyPage\Block\Adminhtml\Page\Edit\Tab\Selection\Option */
?>
<?php $_value       = $block->getElement()->getValue()?>
<?php $_htmlId      = $block->getElement()->getHtmlId() ?>
<?php $_htmlClass   = $block->getElement()->getClass() ?>
<?php $_htmlName    = $block->getElement()->getName() ?>
<?php $_readonly    = $block->getElement()->getReadonly() ?>
<div class="field" id="<?= /* @escapeNotVerified */ $_htmlId?>_container">
    <label class="label"><span><?= $block->escapeHtml($block->getElement()->getLabel()); ?></span></label>

    <div class="admin__field-control control">
        <div id="<?= /* @escapeNotVerified */ $_htmlId?>_data">
            <?= /* @escapeNotVerified */ $block->getValueHtml();?>
        </div>
    </div>
</div>
