<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_ShopbyPage
 */
?>
<?php
/** @var $block \Amasty\ShopbyPage\Block\Adminhtml\Page\Edit\Tab\Selection\Value */
?>
<?php $inputName = $block->escapeHtml($block->getInputName()); ?>
<?php if ($block->getFrontendInput() === 'select') :?>
    <select name="<?= /* @escapeNotVerified */ $inputName?>" class="select admin__control-select">
        <?php foreach ($block->getAttributeOptions() as $_option) : ?>
            <option
                value="<?= /* @escapeNotVerified */ $_option['value'];?>"
                <?= /* @escapeNotVerified */ ($_option['value'] === $block->getEavAttributeValue() ? 'selected' : '')?>
                >
                <?= $block->escapeHtml($_option['label']);?>
            </option>
        <?php endforeach;?>
    </select>

<?php elseif ($block->getFrontendInput() === 'multiselect') : ?>
    <select name="<?= /* @escapeNotVerified */ $inputName?>[]"
            class="select multiselect admin__control-multiselect amasty-shopbypage-selection-multiselect"
            multiple="multiple">
        <?php foreach ($block->getAttributeOptions() as $_option) : ?>
            <option
                value="<?= /* @escapeNotVerified */ $_option['value'];?>"
                <?= /* @escapeNotVerified */ (is_array($block->getEavAttributeValue()) && in_array(
                    $_option['value'],
                    $block->getEavAttributeValue()
                ) ? 'selected' : '')?>
            >
                <?= $block->escapeHtml($_option['label']);?>
            </option>
        <?php endforeach;?>
    </select>
<?php else : ?>
    <input
        value="<?= /* @escapeNotVerified */ $block->getEavAttributeValue()?>"
        name="<?= /* @escapeNotVerified */ $inputName?>"
        class="input-text" type="text"
    />
<?php endif;?>
