<?php
/** @var \Magento\Customer\Block\Form\Edit $block */
/** @var \TMG\Customer\Helper\Customer $helper */
$helper = $this->helper('TMG\Customer\Helper\Customer');
$formData = $helper->getCustomerDataFromDataObject($block->getCustomer());

?>
<form class="form form-edit-account" action="<?php /* @escapeNotVerified */ echo $block->getUrl('customer/account/editPost') ?>" method="post" id="form-validate" enctype="multipart/form-data" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>" autocomplete="off">
    
    <?php echo $block->getBlockHtml('formkey')?>
    
    <?php if($block->getRequest()->getParam('changepass')): ?>;

        <fieldset class="fieldset" id="change-email-password" data-container="change-email-password">
            <legend class="legend"><span data-title="change-email-password"><?php /* @escapeNotVerified */ echo __('Change Password') ?></span></legend><br>
            <div class="field password current required">
                <label class="label" for="current-password"><span><?php /* @escapeNotVerified */ echo __('Current Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="current_password" id="current-password" data-input="current-password" autocomplete="off" />
                </div>
            </div>
            <div class="field new password required" data-container="new-password" data-mage-init='{"passwordStrengthIndicator": {}}'>
                <label class="label" for="password"><span><?php /* @escapeNotVerified */ echo __('New Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="password" id="password"
                           data-password-min-length="<?php echo $block->escapeHtml($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?php echo $block->escapeHtml($block->getRequiredCharacterClassesNumber()) ?>"
                           data-input="new-password"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off" />
                    <div id="password-strength-meter-container" data-role="password-strength-meter" >
                        <div id="password-strength-meter" class="password-strength-meter">
                            <?php /* @escapeNotVerified */ echo __('Password Strength'); ?>:
                            <span id="password-strength-meter-label" data-role="password-strength-meter-label" >
                            <?php /* @escapeNotVerified */ echo __('No Password'); ?>
                        </span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="field confirm password required" data-container="confirm-password">
                <label class="label" for="password-confirmation"><span><?php /* @escapeNotVerified */ echo __('Confirm New Password') ?></span></label>
                <div class="control">
                    <input type="password" class="input-text" name="password_confirmation" id="password-confirmation"
                           data-input="confirm-password"
                           autocomplete="off" />
                </div>
            </div>
            <div class="field choice hidden">
                <input type="checkbox" name="change_password" id="change-password" data-role="change-password" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>" checked="checked" class="checkbox" />
            </div>
        </fieldset>

    <?php else: ?>
    
        <?php echo $block->getLayout()->createBlock('TMG\Customer\Block\Customer\Form\PersonalInformation')
            ->setFormData($formData)->toHtml(); ?>
    
        <?php echo $block->getLayout()->createBlock('TMG\Customer\Block\Customer\Form\CompanyInformation')
            ->setFormData($formData)->setData('is_readonly',true)->toHtml(); ?>

        <div class="field hidden">
            <input type="hidden" name="tmg_" id="change-password" data-role="change-password" value="1" title="<?php /* @escapeNotVerified */ echo __('Change Password') ?>" checked="checked" class="checkbox" />
        </div>

    <?php endif; ?>
    
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="action save primary" title="<?php /* @escapeNotVerified */ echo __('Save') ?>"><span><?php /* @escapeNotVerified */ echo __('Save') ?></span></button>
        </div>
        <div class="secondary">
            <a class="action back" href="<?php echo $block->escapeUrl($block->getBackUrl()) ?>"><span><?php /* @escapeNotVerified */ echo __('Go back') ?></span></a>
        </div>
    </div>
    
</form>

<script>
    require([
        "jquery",
        "mage/mage"
    ], function($) {
        var dataForm = $('#form-validate');
        dataForm.mage('validation', {
            ignore: ':hidden'
        });
    });
</script>