<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
    /** @var \Amasty\ShopbyBase\Model\FilterSetting $filterSetting */
    /** @var \Amasty\Shopby\Block\Navigation\FilterRenderer $block */
    $filterUniqId = $block->escapeId(uniqid());
    $filterCode = $block->escapeHtml($filterSetting->getFilterCode());
?>
<form data-amshopby-filter="<?= $filterCode; ?>" data-amshopby-filter-request-var="<?= $block->getFilter()->getRequestVar(); ?>"
    <?php if ($filterSetting->getEnableOverflowScroll() > 0) : ?>
        style="max-height:<?= $filterSetting->getEnableOverflowScroll() ?>px;
            overflow-y: auto;
            overflow-x: hidden;"
    <?php endif; ?>>
    <ul class="items am-filter-items-<?= $filterCode; ?> amshopby-fly-out-view">
        <?= $categoryTreeHtml; ?>
    </ul>
</form>
<script>
    require(["jquery", "jquery/ui"], function ($) {
        $(window).load( function(){
            $(document).trigger('baseCategory', <?= $block->getCurrentCategoryId();?>);
            addFlyOut();
        });
        $(document).ajaxComplete( function(){
            addFlyOut();
            $(document).trigger('baseCategory', <?= $block->getCurrentCategoryId();?>);
        });

        function addFlyOut() {
            $(".am-filter-items-<?= $filterCode;?>").menu({
                position: { my: "left top", at: "center top+20" }
            });
        }
    });
</script>
