<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/** @var \Amasty\ShopbyBase\Model\FilterSetting $filterCode */
?>

<div class="amshopby-search-box">
    <input type="text"
           class="am-search-box-<?= $filterCode;?>"
           placeholder="<?= $block->escapeHtml(__("Search"))?>" />
</div>

<script type="text/x-magento-init">
            {
                ".am-search-box-<?= $filterCode?>": {
                    "amShopbyFilterSearch": {
                        "highlightTemplate": "<span class='amshopby-hightlighted'>$&</span>",
                        "itemsSelector": ".am-filter-items-<?= $filterCode;?>"
                    }
                }
            }
</script>
