<?php
$cat_id = $this->getCatId();

$tags = $this->getTags();

$limit = (intval(filter_input(INPUT_GET, 'limit')) != 0 ) ? filter_input(INPUT_GET, 'limit') : 12;
$offset = (intval(filter_input(INPUT_GET, 'offset')) != 0 ) ? filter_input(INPUT_GET, 'offset') : 0;
$cat_id = (intval(filter_input(INPUT_GET, 'cat_id')) != 0 ) ? filter_input(INPUT_GET, 'cat_id') : $this->getCatId();

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$this->_storeManager = $storeManager;        
$store_id =  $this->_storeManager->getStore()->getId();
$allstore = array();
array_push($allstore,0);
array_push($allstore,$store_id);

if ($cat_id) {
      $model1 = $objectManager->create('Biztech\Productdesigner\Model\Mysql4\Clipart\Collection')
        ->addFieldToFilter('clipart_id', array('eq' => $cat_id))  
        ->addFieldToFilter('status', array('eq' => 1))
        ->addFieldToFilter('store_id', array('in' => $allstore))
        ->getFirstItem();
}

$model = $objectManager->create('Biztech\Productdesigner\Model\Mysql4\Clipart\Collection')
        ->addFieldToFilter('parent_categories', array('eq' => $cat_id))
        ->addFieldToFilter('status', array('eq' => 1))
        ->addFieldToFilter('store_id', array('in' => $allstore));
      

$clipart_col = $model->getData();
$clipartIds = array();
foreach ($clipart_col as $clipartc) {
    $clipartIds[] = $clipartc['clipart_id'];
}
$sub_cat_id = implode(',', $clipartIds);
?>
<?php
if ($cat_id):
    $images = $objectManager->create('Biztech\Productdesigner\Model\Mysql4\Clipartmedia\Collection')->addFieldToFilter('tags', array('like' => '%' . $tags . '%'))->addFieldToFilter('disabled', array('neq' => '1'));
    ?>
    <?php
    if ($sub_cat_id) {
        $Cats = array();
        foreach (explode(',', $sub_cat_id) as $subCats) {
            $Cats[] = $subCats;
        }
        $Cats[] = $cat_id;
        $images = $images->addFieldToFilter('clipart_id', array('in' => $Cats));
        $images->getSelect()->limit($limit);
    } else {
        $images = $images->addFieldToFilter("clipart_id", array("eq" => $cat_id));
        $images->getSelect()->limit($limit);
    }
endif;
?>
<ul id="image_list" class="product_list">
    <?php $base_url = $block->getbaseurl(); ?>
    <?php
    if (isset($images)) {
        foreach ($images as $image):
            ?>
            <li>
                <div class="clipart-img-wrapper">
                    <img src="<?php echo $base_url . 'productdesigner/clipart/' . $image['image_path']; ?>" class="product-image clipart-image" data-orig-url="<?php echo $base_url . 'productdesigner/clipart/' . $image['image_path']; ?>" data-price="<?php echo $image['price'] ?>" alt="<?php echo $image['label'] ?>" title="<?php echo $image['label'] ?>"></div>
            </li>
        <?php endforeach; ?>
            <?php if (count($images) == 0): ?>
            <li class="note-message"> <span class="a-center"> <?php echo __("Sorry, no images found."); ?></span></li>
            <?php endif;
        }
        ?>

</ul>