<?php
$cat_id = $this->getCatId();
$tags = $this->getTags();
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

    $limit = (intval(filter_input(INPUT_GET, 'limit')) != 0 ) ? filter_input(INPUT_GET, 'limit') : 12;
    $offset = (intval(filter_input(INPUT_GET, 'offset')) != 0 ) ? filter_input(INPUT_GET, 'offset') : 0;
    $cat_id = (intval(filter_input(INPUT_GET, 'cat_id')) != 0 ) ? filter_input(INPUT_GET, 'cat_id') : $this->getCatId();

if (!$cat_id) {
//    $cat_id = $block->getDefaultShapesCategory();
//    $category = $objectManager->create('Biztech\Productdesigner\Model\Resource\Shapes\Collection')->addFieldToFilter("status",array("neq" => 1))->getData();
//    foreach($category as $c)
//    {
//        if($c['shapes_id'] == $cat_id)
//        {
//            $cat_id = 'Select a Catagory';
//        }
//    }
}
//$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$model = $objectManager->create('Biztech\Productdesigner\Model\Mysql4\Shapes\Collection')->addFieldToFilter('parent_categories', array('eq' => $cat_id))->addFieldToFilter('status', array('eq' => 1));
$shape_col = $model->getData();
$shapeIds = array();
foreach ($shape_col as $shapec) {

    $shapeIds[] = $shapec['shapes_id'];
}


$sub_cat_id = implode(',', $shapeIds);
?>
<?php
if ($cat_id):
    $images = $objectManager->create('Biztech\Productdesigner\Model\Mysql4\Shapesmedia\Collection')->addFieldToFilter('tags', array('like' => '%' . $tags . '%'))->addFieldToFilter('disabled', array('neq' => '1'));
    ?>
    <?php
    if ($sub_cat_id) {
        $Cats = array();
        foreach (explode(',', $sub_cat_id) as $subCats) {
            $Cats[] = $subCats;
        }
        $Cats[] = $cat_id;
        $images = $images->addFieldToFilter('shapes_id', array('in' => $Cats));
        $images->getSelect()->limit($limit);
    } else {
        $images = $images->addFieldToFilter("shapes_id", array("eq" => $cat_id));
        $images->getSelect()->limit($limit);
    }
endif;
?>
<ul id="image_list_shapes" class="image_list product_list">
<?php $base_url = $block->getbaseurl(); ?>

    <?php
    if (isset($images)) {
        foreach ($images as $image):
            ?>
            <li>
                <img src="<?php echo $base_url . 'productdesigner/shapes/' . $image['image_path']; ?>" class="product-image shapes-image" data-orig-url="<?php echo $base_url . 'productdesigner/shapes/' . $image['image_path']; ?>" data-price="<?php echo $image['price'] ?>" alt="<?php echo $image['label'] ?>" title="<?php echo $image['label'] ?>">
            </li>
        <?php endforeach; ?>
        <?php if (count($images) == 0 && $cat_id): ?>
            <li class="note-message"> <span class="a-center"> <?php echo __("Sorry, no images found."); ?></span></li>
            <?php endif;
        }
        ?>

</ul>