<?php
/**
 * Template Name: Slider Revolution Blank Template
 * Template Post Type: post, page
 * The template for displaying RevSlider on a blank page
 */
?>
<!DOCTYPE html>
<html <?php $frameworkHelper->language_attributes(); ?> class="no-js">
	<head>
		<meta charset="<?php $frameworkHelper->bloginfo('charset'); ?>">
		<meta name="viewport" content="width=device-width">
		<link rel="profile" href="http://gmpg.org/xfn/11">
		<link rel="pingback" href="<?php $frameworkHelper->bloginfo('pingback_url'); ?>">
        <script>
            var require = {
                "baseUrl": "<?php echo $frameworkHelper->getAssetUrl('', [], true); ?>"
            };
        </script>
        <script type="text/javascript" src="<?php echo $frameworkHelper->getAssetUrl('requirejs/require.js', [], true); ?>"></script>
        <script type="text/javascript" src="<?php echo $frameworkHelper->getAssetUrl('requirejs-config.js', [], true); ?>"></script>
        <link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $frameworkHelper->getAssetUrl('public/assets/css/rs6.css', []); ?>" />
		<style type="text/css">
			body:before { display:none !important}
			body:after { display:none !important}
			body { background:transparent}
		</style>
        <?php echo $headIncludes; ?>
		<?php echo $frameworkHelper->includeEnqueuedAssets(); ?>
	</head>
	<body <?php $frameworkHelper->body_class(); ?>>
		<div>
			<?php echo $content; ?>
		</div>
		<?php $frameworkHelper->wp_footer(); ?>
	</body>
</html>