<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<script type="text/x-magento-init">
        {
            ".products-grid": {
                "amShopbySwatchesChoose": {
                    "listSwatches": <?= /* @escapeNotVerified */ $block->getSwatchesByJson();?>
                }
            }
        }
</script>
