<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_Shopby
 */
?>
<?php
/**
 * @var $block \Amasty\Shopby\Block\Navigation\FilterCollapsing
 */

?>

<script type="text/x-magento-init">
            {
                ".sidebar #narrow-by-list": {
                    "accordion": {
                        "multipleCollapsible": true,
                        "active": [<?= $block->escapeHtml(implode(",", $block->getFiltersExpanded()))?>]
                    }
                }
            }
</script>
