<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_ShopbyBrand
 */
?>
<?php
/** @var \Amasty\ShopbyBrand\Block\Widget\BrandList $block */
$items = $block->getIndex();
$columns = abs((int)$block->getData('columns'));
$brandLetters = $block->getAllLetters();
$isShowCount = $block->getData('show_count');
$isShowImages = $block->getData('show_images');
$imgWidth = $block->getImageWidth();
$imgHeight = $block->getImageHeight();
$isShowSearch = $block->getData('show_search');
$isShowFilter = $block->getData('show_filter');
$filterDisplayAll = $block->getData('filter_display_all');
$display_zero = $block->getData('display_zero');
$width = floor(100 / $columns);
?>
<style>
    .bare-list .ambrands-image {
        max-width: <?= $block->escapeHtml($imgWidth);?>px;
        max-height: <?= $block->escapeHtml($imgHeight);?>px;
    }

    .brand-item .am-image-wrapper {
        height: <?= $block->escapeHtml($imgWidth);?>px;
    }

    .brand-item {
        max-width: <?= $block->escapeHtml($imgWidth);?>px;
        min-width: <?= $block->escapeHtml($imgWidth);?>px;
        min-height: <?= $block->escapeHtml($imgWidth+30);?>px;
    }
    .brand-item .no-img {
        width: <?= $block->escapeHtml($imgWidth);?>px;
        line-height: <?= $block->escapeHtml($imgWidth);?>px;
        font-size: <?= $block->escapeHtml($imgWidth*0.65);?>px;
    }
    @media (min-width: 768px) {
        .brand-images .brands-letter {
            width:<?= $block->escapeHtml($width) ?>%;
        }
    }
</style>

<div class="content">
<?php if ($items) : ?>
    <?php if ($isShowSearch || $isShowFilter) :?>
        <div class="brands-filters">
            <?= $block->getSearchHtml(); ?>
            <?php if ($isShowFilter) :?>
                <div class="letters">
                    <div class="letters-box">
                        <a href="javascript:void(0)" class="letter -letter-all" data-ambrands-js="filter-letter" title="<?= $block->escapeHtml(__('All Brands'))?>">
                            <?= $block->escapeHtml(__('All Brands'))?>
                        </a>
                    </div>
                    <div class="letters-box">
                        <?php if ($filterDisplayAll) :?>
                            <?php foreach (array_merge(range('A', 'Z'), ['#']) as $letter) :?>
                                <a href="javascript:void(0)" data-ambrands-js="filter-letter"
                                   class="letter <?= (!(in_array($letter, $brandLetters)))
                                       ? '-disabled'
                                       : 'letter-' . $block->escapeHtml($letter)?>">
                                    <?= $block->escapeHtml($letter)?></a>
                            <?php endforeach;  ?>
                        <?php else : ?>
                            <?php foreach ($brandLetters as $letter) :?>
                                <a href="javascript:void(0)" class="letter letter-<?= $block->escapeHtml($letter)?>">
                                    <?= $block->escapeHtml($letter)?>
                                </a>
                            <?php endforeach;  ?>
                        <?php endif; ?>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    <?php endif; ?>
<?php foreach ($items as $letters) : ?>
    <div class="brand-images">
    <?php foreach ($letters as $letter => $options) : ?>
        <dl class="brands-letter letter-<?= $block->escapeHtml($letter)?>" data-ambrands-js="brand-letter">
            <dt class="letter">
                <span class="title"><?= $block->escapeHtml($letter) ?></span>
            </dt>
            <dd>
                <ul class="bare-list">
                <?php foreach ($options as $o) : ?>
                    <li class="brand-item" <?= $block->getTooltipAttribute($o);?>>
                        <a href="<?= $block->escapeUrl($o['url']) ?>"
                           class="item"
                           title="<?= $block->escapeHtml($o['label']) ?>">
                            <?php if ($o['img'] && $isShowImages) : ?>
                                <div class="am-image-wrapper">
                                    <img class="ambrands-image"
                                            src="<?= $block->escapeUrl($o['img']) ?>"
                                         title="<?= $block->escapeHtml($o['alt']) ?>"
                                         alt="<?= $block->escapeHtml($o['alt']) ?>" />
                                </div>
                            <?php else : ?>
                                <div class="am-image-wrapper">
                                    <p class="no-img"><?= $block->escapeHtml($letter) ?></p>
                                </div>
                            <?php endif ?>
                                <p class="label"><?= $block->escapeHtml($o['label']) ?></p>
                            <?php if ($isShowCount) : ?>
                                <p class="count"><?= $block->escapeHtml($o['cnt']) ?></p>
                            <?php endif; ?>
                        </a>
                    </li>
                <?php endforeach ?>
                </ul>
            </dd>
        </dl>
    <?php endforeach ?>
    </div>
<?php endforeach ?>
    <div style="clear:both;"></div>
<?php else : ?>
    Please select brand attribute in Stores -> Configuration -> Amasty Extensions -> Improved Layered Navigation:
    Brands.
<?php endif ?>
</div>

<script>
    require([
        'jquery',
        'Amasty_ShopbyBrand/js/brand-filter',
        'domReady!'
    ], function ($) {
        $('[data-ambrands-js="filter-letter"]').on('click', function(e) {
            e.preventDefault();
            $(this).applyBrandFilter('[data-ambrands-js="brand-letter"]');
        });
    });

    <?php if ($block->isTooltipEnabled()) :?>
    require([
        'jquery',
        "mage/tooltip"
    ], function ($) {
        $('[data-amshopby-js="brand-tooltip"]').tooltip({
            position: {
                my: "left-20 bottom",
                at: "right top",
                collision: "flip flip",
                using: function (position, feedback) {
                    $(this).css(position);
                    $("<div>")
                        .addClass("arrow")
                        .addClass(feedback.vertical)
                        .addClass(feedback.horizontal)
                        .appendTo(this);
                }
            },
            tooltipClass: "amshopby-brand-tooltip",
            content: function () {
                var current = $(this).is('li') ? $(this) : $(this).parent();
                return current.data('tooltip-content');
            }
        });
    });
    <?php endif ?>
</script>
