<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2017 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php /** @var $block \Blackbird\ContentManager\Block\Adminhtml\ContentType\Edit\Tab\Layout\Templates\Item\Field\Misc */ ?>
<script id="contenttype-content-layout-item-field-country" type="text/x-magento-template">
    <!-- todo add extra params -->
</script>

<script id="contenttype-content-layout-item-field-currency" type="text/x-magento-template">
    <!-- todo add extra params -->
</script>

<script id="contenttype-content-layout-item-field-locale" type="text/x-magento-template">
    <!-- todo add extra params -->
</script>
