<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2017 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php /** @var $block \Blackbird\ContentManager\Block\Adminhtml\ContentType\Edit\Tab\Layout\Templates\Item\Field\Select */ ?>
<script id="contenttype-content-layout-item-field-checkbox" type="text/x-magento-template">
    <div class="field id="contenttype-content-layout-item-field-checkbox">
        <label class="label"><?= __('Format') ?></label>
        <div class="control">
            <div class="contenttype-format format-checkbox">
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_checkbox_lvalue"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="checkbox_list_values"
                       <% if (data.format == 'checkbox_list_values') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_checkbox_lvalue">
                    <?= __('Display all values as a list (ul > li)') ?>
                </label>
                <br />
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_checkbox_ltitle"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="checkbox_list_titles"
                       <% if (data.format == 'checkbox_list_titles' || data.format == '') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_checkbox_ltitle">
                    <?= __('Display all titles as a list (ul > li)') ?>
                </label>
                <br />
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_checkbox_cvalue"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="checkbox_comma_values"
                       <% if (data.format == 'checkbox_comma_values') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_checkbox_cvalue">
                    <?= __('Concatenate all values by a comma (value1, value2)') ?>
                </label>
                <br />
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_checkbox_ctitle"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="checkbox_comma_titles"
                       <% if (data.format == 'checkbox_comma_titles') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_checkbox_ctitle">
                    <?= __('Concatenate all titles by a comma (value1, value2)') ?>
                </label>
            </div>
        </div>
    </div>
</script>

<script id="contenttype-content-layout-item-field-multiple" type="text/x-magento-template">
    <div class="field id="contenttype-content-layout-item-field-multiple">
        <label class="label"><?= __('Format') ?></label>
        <div class="control">
            <div class="contenttype-format format-multiple">
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_multiple_lvalue"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="multiple_list_values"
                       <% if (data.format == 'multiple_list_values') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_multiple_lvalue">
                    <?= __('Display all values as a list (ul > li)') ?>
                </label>
                <br />
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_multiple_ltitle"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="multiple_list_titles"
                       <% if (data.format == 'multiple_list_titles' || data.format == '') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_multiple_ltitle">
                    <?= __('Display all titles as a list (ul > li)') ?>
                </label>
                <br />
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_multiple_cvalue"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="multiple_comma_values"
                       <% if (data.format == 'multiple_comma_values') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_multiple_cvalue">
                    <?= __('Concatenate all values by a comma (value1, value2)') ?>
                </label>
                <br />
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_multiple_ctitle"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="multiple_comma_titles"
                       <% if (data.format == 'multiple_comma_titles') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_multiple_ctitle">
                    <?= __('Concatenate all titles by a comma (value1, value2)') ?>
                </label>
            </div>
        </div>
    </div>
</script>

<script id="contenttype-content-layout-item-field-radio" type="text/x-magento-template">
    <div class="field id="contenttype-content-layout-item-field-radio">
        <label class="label"><?= __('Format') ?></label>
        <div class="control">
            <div class="contenttype-format format-radio">
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_radio_value"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="radio_select_value"
                       <% if (data.format == 'radio_select_value') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_radio_value">
                    <?= __('Display value') ?>
                </label>
                <br />
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_radio_title"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="radio_select_title"
                       <% if (data.format == 'radio_select_title' || data.format == '') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_radio_title">
                    <?= __('Display title') ?>
                </label>
            </div>
        </div>
    </div>
</script>

<script id="contenttype-content-layout-item-field-drop_down" type="text/x-magento-template">
    <div class="field id="contenttype-content-layout-item-field-drop_down">
        <label class="label"><?= __('Format') ?></label>
        <div class="control">
            <div class="contenttype-format format-drop_down">
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_dropdown_value"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="drop_select_value"
                       <% if (data.format == 'drop_select_value') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_dropdown_value">
                    <?= __('Display value') ?>
                </label>
                <br />
                <input type="radio" class="checkbox layout_field_format required-entry _required"
                       id="layout-item-field-<%- data.id %>-display_dropdown_title"
                       name="layout[item][field][<%- data.id %>][format]"
                       value="drop_select_title"
                       <% if (data.format == 'drop_select_title' || data.format == '') { %>checked="checked"<% } %>
                />
                <label for="layout-item-field-<%- data.id %>-display_dropdown_title">
                    <?= __('Display title') ?>
                </label>                
            </div>
        </div>
    </div>
</script>
