<div>
    <button type="button" id="virtual-tool-btn" class="action primary"><?php echo __("Custom Product") ?></button>
</div>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
$_sku = $_product->getSKU();
$_brand = $_product->getBrandName();
echo ($_brand);
echo ($_sku);
$url = "/tool/product/custom" . "?sku=BG269&supplierId=323";
echo ($url);
$url1 = "/123";
?>
<script>
    require([
        'jquery',
        'popupWindow'
    ], function ($) {
        'use strict';

        $("#virtual-tool-btn").popupWindow({
            "windowURL": "<?=$url;?>",
            "centerScreen": 1,
            "width": 1000,
            "height": 800,
        });
    });
</script>