<?php
/**
 * @author Amasty Team
 * @copyright Copyright (c) 2019 Amasty (https://www.amasty.com)
 * @package Amasty_ShopbyBrand
 */
?>
<?php
$class = 'amshopby-morefrom';
$image = 'upsell_products_list';
/* @var $block \Amasty\ShopbyBrand\Block\Catalog\Product\ProductList\MoreFrom */
$title = $block->getTitle();
$items = $block->getItemCollection();

$showAddTo = true;
$showCart = true;
$templateType = null;
$description = false;
?>

<div class="block <?= /* @escapeNotVerified */ $class ?>">
    <div class="block-title title">
        <strong id="block-<?= /* @escapeNotVerified */ $class ?>-heading" role="heading" aria-level="2">
            <?= /* @escapeNotVerified */ $title ?>
        </strong>
    </div>
    <div class="block-content content" aria-labelledby="block-<?= /* @escapeNotVerified */ $class ?>-heading">
        <div class="products wrapper grid products-grid products-morefrom">
            <ol class="products list items product-items">
                <?php foreach ($items as $_item) : ?>
                    <li class="item product product-item">

                        <div class="product-item-info">
                            <?= /* @escapeNotVerified */ '<!-- ' . $image . '-->' ?>
                            <a href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>"
                               class="product photo product-item-photo">
                                <?= $block->getImage($_item, $image)->toHtml() ?>
                            </a>
                            <div class="product details product-item-details">
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       title="<?= $block->escapeHtml($_item->getName()) ?>"
                                       href="<?= /* @escapeNotVerified */ $block->getProductUrl($_item) ?>">
                                        <?= $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>

                                <?= /* @escapeNotVerified */ $block->getProductPrice($_item) ?>

                                <?php if ($showAddTo || $showCart) : ?>
                                    <div class="product actions product-item-actions">
                                        <?php if ($showCart) : ?>
                                            <div class="actions-primary">
                                                <?php if ($_item->isSaleable()) : ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)) : ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl": {"url": "<?= /* @escapeNotVerified */ $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button"
                                                                title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php $postDataHelper = $this->helper(\Magento\Framework\Data\Helper\PostHelper::class);
                                                        $postData = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?= /* @escapeNotVerified */ $postData ?>'
                                                                type="button"
                                                                title="<?= /* @escapeNotVerified */ __('Add to Cart') ?>">
                                                            <span><?= /* @escapeNotVerified */ __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else : ?>
                                                    <?php if ($_item->getIsSalable()) : ?>
                                                        <div class="stock available">
                                                            <span><?= /* @escapeNotVerified */ __('In stock') ?></span>
                                                        </div>
                                                    <?php else : ?>
                                                        <div class="stock unavailable">
                                                            <span><?= /* @escapeNotVerified */ __('Out of stock') ?></span>
                                                        </div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                                <div data-role="add-to-links" class="actions-secondary">
                                                    <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow()): ?>
                                                        <a href="#"
                                                           class="action towishlist"
                                                           title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                           aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                           data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_item); ?>'
                                                           data-action="add-to-wishlist"
                                                           role="button">
                                                            <span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
                                                        </a>
                                                    <?php endif; ?>
                                                    <?php
                                                    $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);
                                                    ?>
                                                    <a href="#"
                                                       class="action tocompare"
                                                       title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_item); ?>'
                                                       role="button">
                                                        <span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
                                                    </a>
                                                </div>
                                            </div>
                                        <?php endif; ?>

                                        <?php if ($showAddTo) : ?>
                                            <div class="secondary-addto-links actions-secondary" data-role="add-to-links">
                                                <?php if ($addToBlock = $block->getChildBlock('addto')) : ?>
                                                    <?= $addToBlock->setProduct($_item)->getChildHtml() ?>
                                                <?php endif; ?>
                                            </div>
                                        <?php endif; ?>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </li>
                <?php endforeach ?>
            </ol>
        </div>
    </div>
</div>
