<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2017 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>

<script>
require([
    "jquery",
    "Blackbird_ContentManager/js/contenttype"
], function(jQuery){
    jQuery(function ($) {
        var contentSet = $('#contenttype_informations_fieldset');
        contentSet.contenttype();
    });
});
</script>
