<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2017 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php /** @var $block \Blackbird\ContentManager\Block\View\Field */ ?>
<?php
    $_content = $block->getContent();
    $_params = $block->getParams();
    $_identifier = $block->getIdentifier();
    $_helper = $this->helper(\Blackbird\ContentManager\Helper\Content\Data::class);
    
    // Default value
    $_labelType = 0;
    $_htmlLabelTag = 'label';
    $_htmlTag = 'div';
    $_htmlId = '';
    $_htmlClass = '';
    
    // custom_field override
    if (isset($_params['custom_field'])) {
        $_customField = $_params['custom_field'];
        $_customFieldId = $_customField->getId();
        $_label = __($_customField->getTitle());
        $_type = 'file_filename_without';
        $_extra = '';
    }
    
    // Layout override
    if (isset($_params['layout'])) {
        $_layoutOption = $_params['layout'];
        $_labelType = $_layoutOption->getLabel();
        $_htmlLabelTag = $_layoutOption->getHtmlLabelTag();
        $_htmlTag = $_layoutOption->getHtmlTag();
        $_htmlId = $_layoutOption->getHtmlId();
        $_htmlClass = $_layoutOption->getHtmlClass();
        $_format = unserialize($_layoutOption->getFormat());
        $_type = $_format['type'];
        $_extra = __($_helper->applyPattern($_content, $_format['extra']));
    }
    
    // Extra params override
    if (isset($_params['params'])) {
        $_extraParams = $_params['params'];
        if (isset($_extraParams['label'])) $_label = $_extraParams['label'];
        if (isset($_extraParams['label_type'])) $_labelType = $_extraParams['label_type'];
        if (isset($_extraParams['html_label_tag'])) $_htmlLabelTag = $_extraParams['html_label_tag'];
        if (isset($_extraParams['html_tag'])) $_htmlTag = $_extraParams['html_tag'];
        if (isset($_extraParams['html_id'])) $_htmlId = $_extraParams['html_id'];
        if (isset($_extraParams['html_class'])) $_htmlClass = $_extraParams['html_class'];
        if (isset($_extraParams['type'])) $_type = $_extraParams['type'];
        if (isset($_extraParams['extra'])) $_extra = $_extraParams['extra'];
    }
?>
<?php if ($_htmlTag) : ?><<?php echo $_htmlTag; ?> class="ct-field ct-field-<?php echo $block->getType(); ?> <?php echo $_htmlClass; ?>" id="<?php if ($_htmlId) : ?><?php echo $_htmlId; ?><?php else: ?>ct-field-<?php echo $_customFieldId; ?><?php endif; ?>"><?php endif; ?>
    <?php /*Label over*/ ?>
    <?php if ($_labelType == 1) : ?><?php if ($_htmlLabelTag) : ?><<?php echo $_htmlLabelTag; ?> class="label"><?php endif; ?><?php echo $_label; ?><?php if ($_htmlLabelTag) : ?></<?php echo $_htmlLabelTag; ?>><?php endif; ?><?php endif; ?>

    <?php /*Value wrapper start*/ ?>
    <?php if ($_labelType == 1 || $_labelType == 2) : ?><div class="ct-value"><?php endif; ?>

        <?php /*Label inline*/ ?>
        <?php if ($_labelType == 3) : ?><?php if ($_htmlLabelTag) : ?><<?php echo $_htmlLabelTag; ?> class="label"><?php endif; ?><?php echo $_label; ?><?php if ($_htmlLabelTag) : ?></<?php echo $_htmlLabelTag; ?>><?php endif; ?><?php endif; ?>

        <?php /*Value*/ ?>
        <a href="<?php echo $_content->getFile($_identifier); ?>" class="ct-file-link" target="_blank">
            <span>
                <?php
                    switch($_type) {
                        case 'file_filename_with':
                            echo $_content->getData($_identifier);
                            break;
                        case 'file_custom_label':
                            echo $_extra;
                            break;
                        case 'file_filename_without': 
                        default:
                            if (strrpos($_content->getData($_identifier), '.') !== false) {
                                echo substr($_content->getData($_identifier), 0, strrpos($_content->getData($_identifier), '.'));
                            } else {
                                echo $_content->getData($_identifier);
                            }
                            break;
                    }
                ?>
            </span>
        </a>
        
    <?php /*Value wrapper end*/ ?>
    <?php if ($_labelType == 1 || $_labelType == 2) : ?></div><?php endif; ?>
    <?php /*Label below*/ ?>
    <?php if ($_labelType == 2) : ?><?php if ($_htmlLabelTag) : ?><<?php echo $_htmlLabelTag; ?> class="label"><?php endif; ?><?php echo $_label; ?><?php if ($_htmlLabelTag) : ?></<?php echo $_htmlLabelTag; ?>><?php endif; ?><?php endif; ?>
<?php if ($_htmlTag) : ?></<?php echo $_htmlTag; ?>><?php endif; ?>
