<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<script type="text/javascript" src="https://virtualmarketingcart.com/js/bootstrap.min.js"></script>
<script type="text/javascript"
        src="https://virtualmarketingcart.com/bundles/bazingajstranslation/js/translator.min.js"></script>

<div id="ob-virtualmarketingcart">
    <input id="ob-virtualmarketingcart-sku" type="hidden" value="<?=$block->getData("sku");?>">
    <input id="ob-virtualmarketingcart-supplier" type="hidden" value="<?=$block->getData("supplierId");?>">
    <input id="ob-virtualmarketingcart-culture" type="hidden" value="en_us">
    <input type="button" class="ob-btvirtualloadcontent" style="display:none;"/>
    <div id="uploadModal" data-keyboard="false" data-backdrop="static" tabindex="-1" role="dialog"
         aria-labelledby="myModalLabel" aria-hidden="true" class="modal obvirtual-modal-div fade"></div>
</div>

<script type="text/javascript" src="https://virtualmarketingcart.com/js/virtualintegration.js"></script>

<script>
    $(document).on("readystatechange", function() {
        if (this.readyState === 'complete') $(".virtual-button").trigger("click");
        $(".virtual-button").hide();
    });
</script>