<?php
/**
* Copyright © 2015 Magento. All rights reserved.
* See COPYING.txt for license details.
*/
// @codingStandardsIgnoreFile
/** @var $block \Magento\Backend\Block\Media\Uploader */
?>
<?php $id = $this->getRequest()->getParam('id');?>




<div id="clipart_gallery_content"
class='gallery'
data-mage-init='{"productGallery":{"template":"#clipart_gallery_content-template"}}'
data-images="<?php /* @escapeNotVerified */ echo $block->escapeHtml($block->getImagesJson($id)) ?>"
data-types=""
>
<!-- uploader.phtml -->

<div class="image image-placeholder clipart-wrapper">
    <!-- uploader.phtml -->
    <div id="clipart_uploader" class="uploader">
        <div class="fileinput-button form-buttons button">
            <span><?php /* @escapeNotVerified */ echo __('Browse Files...') ?></span>
            <input id="fileupload" type="file" name="clipart-image"
            data-url="<?php /* @escapeNotVerified */ echo $this->getUrl('productdesigner/clipart_gallery/upload') ?>" multiple="multiple"/>
        </div>
        <div class="clear"></div>
        <script id="clipart_uploader-template" type="text/x-magento-template">

        </script>
    </div>


    <img class="spacer"
    src="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('images/spacer.gif')?>"/>
    <p class="image-placeholder-text">
        <?php /* @escapeNotVerified */ echo __('Click here or drag and drop to add images.'); echo ' (';echo __('Accepted Files : JPG, JPEG, PNG, SVG');echo ' )';
        ?></p>
    </div>

    


    <script>
        require([
            "jquery",
            'mage/template',
            'Magento_Ui/js/modal/alert',
            "mage/translate",
            "jquery/file-uploader"
            ], function ($, mageTemplate, alert) {
                $('#fileupload').fileupload({
                    dataType: 'json',
                    dropZone: '[data-tab-panel=image-management]',
                    sequentialUploads: true,
                    acceptFileTypes: /(\.|\/)(gif|jpe?g|png)$/i,
                    add: function (e, data) {

                        var progressTmpl = mageTemplate('#clipart_uploader-template'),
                        fileSize,
                        tmpl;
                        $.each(data.files, function (index, file) {
                            debugger;
                            fileSize = typeof file.size == "undefined" ?
                            $.mage.__('We could not detect a size.') :
    //byteConvert(file.size);
                        data.fileId = Math.random().toString(33).substr(2, 18);
                        tmpl = progressTmpl({
                            data: {
                                name: file.name,
                                size: fileSize,
                                id: data.fileId
                            }
                        });
                        $(tmpl).appendTo('#clipart_uploader');
                    });                    
                        $(this).fileupload('process', data).done(function () {
                            data.submit();
                        });
                    },
                    done: function (e, data) {

                        if(!data.result.error) {
                            $('#clipart_gallery_content').trigger('addItem', data.result);
                        } else {
                            alert({
                                content: data.result.error,
                                actions: {
                                    always: function(){}
                                }
                            });
                        }                      
                    },
                });

                $('#fileupload').fileupload('option', {
                    process: [{
                        action: 'load',
                        fileTypes: /^image\/(gif|jpeg|png)$/
                    }, {
                        action: 'resize',
                        maxWidth: <?php /* @escapeNotVerified */ echo \Magento\Framework\File\Uploader::MAX_IMAGE_WIDTH ?> ,
                        maxHeight: <?php /* @escapeNotVerified */ echo \Magento\Framework\File\Uploader::MAX_IMAGE_HEIGHT ?>
                    }, {
                        action: 'save'
                    }]
                });
            });
        </script>
        <!-- uploader.phtml -->



        <script id="clipart_gallery_content-template" type="text/x-magento-template">

            <tr class="headings image item clipart-wrapper <% if (data.disabled == 1) { %>hidden-for-front<% } %>"
                data-role="image">
                <input type="hidden"
                name="clipart[<%- data.file %>][image_id]"
                value="<%- data.image_id %>"
                class="path"/>
                <input type="hidden"
                name="clipart[<%- data.file %>][file]"
                value="<%- data.file %>"
                class="path"/>
                <input type="hidden"
                name="clipart[<%- data.file %>][state]"
                value="<%- data.state %>"
                class="path"/>
                <td>
                    <img class="clipart-image" src="<%- data.url %>" alt="<%- data.label %>"/>
                </td>
                <td>
                    <input type="text" value="<%- data.label %>" class="clipart-label" name="clipart[<%- data.file %>][label]" placeholder="Label"/>
                </td>
                <td>
                    <input type="text" value="<%- data.tags %>" class="clipart-tags" name="clipart[<%- data.file %>][tags]" placeholder="Tags"/>
                </td>
                <td>
                    <input type="text" value="<%- data.position %>" class="clipart-sort" name="clipart[<%- data.file %>][sort]" placeholder="Position"/>
                </td>
                <td>
                    <span><?php /* @escapeNotVerified */ echo __('Remove');
                    ?></span>
                    <input type="checkbox" class="clipart-remove" name="clipart[<%- data.file %>][remove]"/>
                </td>
                <td>
                    <span><?php /* @escapeNotVerified */ echo __('Exclude');?></span>
                    <input type="checkbox" class="clipart-exclude" name="clipart[<%- data.file %>][exclude]" <% if (data.disabled == 1) { %>checked<% } %>/>
                </td>
            </tr>

        </script>   


