<?php
/**
 * BSS Commerce Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://bsscommerce.com/Bss-Commerce-License.txt
 *
 * @category   BSS
 * @package    Bss_InfiniteScroll
 * @author     Extension Team
 * @copyright  Copyright (c) 2018-2019 BSS Commerce Co. ( http://bsscommerce.com )
 * @license    http://bsscommerce.com/Bss-Commerce-License.txt
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Bss\InfiniteScroll\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;

$size = $block->getDefaultSize();
?>
<p class="toolbar-amount" id="toolbar-amount">
    <?php /* @escapeNotVerified */ echo __(
        '%1 Items of '.$size,
        '<span class="toolbar-number">' . ($block->getLastNum() - $block->getFirstNum() + 1) . '</span>'
    ) ?>
</p>
