<?php /** @var \Biztech\Test\Block\Items $block */ ?>

<?php
?>
<body>
    <div class="container">
        <span class="btn btn-success">
            <i class="glyphicon glyphicon-plus"></i>
            <span>Select files...</span>
            <!-- The file input field used as target for the file upload widget -->
            <input id="fileupload" type="file" name="files[]" multiple>
        </span>
        <div id="progress" class="progress">
            <div class="progress-bar progress-bar-success"></div>
        </div>
        <div id="files" class="files"></div>
    </div>
    <script>
        /*jslint unparam: true */
        /*global window, $ */
//        
//      $('#fileupload').fileupload({
//                url: url,
//                dataType: 'json',
//                done: function (e, data) {
//                    
//                    $.each(data.result.files, function (index, file) {
//                        $('<p/>').text(file.name).appendTo('#files');
//                    });
//                },
//                progressall: function (e, data) {
//                    var progress = parseInt(data.loaded / data.total * 100, 10);
//                    $('#progress .progress-bar').css(
//                            'width',
//                            progress + '%'
//                            );
//                }
//            });
    </script>
</body>