<?php
/**
 * ITORIS
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the ITORIS's Magento Extensions License Agreement
 * which is available through the world-wide-web at this URL:
 * http://www.itoris.com/magento-extensions-license.html
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to sales@itoris.com so we can send you a copy immediately.
 *
 * DISCLAIMER
 *
 * Do not edit or add to this file if you wish to upgrade the extensions to newer
 * versions in the future. If you wish to customize the extension for your
 * needs please refer to the license agreement or contact sales@itoris.com for more information.
 *
 * @category   ITORIS
 * @package    ITORIS_M2_PRODUCT_TABS
 * @copyright  Copyright (c) 2016 ITORIS INC. (http://www.itoris.com)
 * @license    http://www.itoris.com/magento-extensions-license.html  Commercial License
 */

namespace Itoris\Producttabsslider\Model;
use Magento\Framework\DataObject\IdentityInterface;
class ProductTabs extends \Magento\Catalog\Model\AbstractModel implements IdentityInterface{
    /**
     * Constants for keys of data array. Identical to the name of the getter in snake case
     */
    const TAB_ID = 'tab_id';
    /**
     * CMS page cache tag
     */
    const CACHE_TAG = 'itoris_product_tabs';
    /**
     * @var string
     */
    protected $_cacheTag = 'itoris_product_tabs';

    /**
     * Prefix of model events names
     *
     * @var string
     */
    protected $_eventPrefix = 'itoris_product_tabs';

    /**
     * Initialize resource model
     *
     * @return void
     */
    protected function _construct()
    {
        $this->_init('Itoris\Producttabsslider\Model\ResourceModel\ProductTabs');
        parent::_construct(); // TODO: Change the autogenerated stub
    }
    /**
     * Return unique ID(s) for each object in system
     *
     * @return array
     */
    public function getIdentities()
    {
        return [self::CACHE_TAG . '_' . $this->getId()];
    }
    /**
     * Get ID
     *
     * @return int|null
     */
    public function getId()
    {
        return $this->getData(self::TAB_ID);
    }

    public function setId($id)
    {
        return $this->setData(self::TAB_ID, $id);
    }



}