<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2017 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php /** @var $block \Blackbird\ContentManager\Block\View\Field\Country */ ?>
<?php
$_identifier = $block->getIdentifier();
$_content = $block->getContent();
$_countryCollection = $block->getCountryCollection();
?>
<?php if ($_countryCollection->count()): ?>
    <ul class="country-list" id="country-list-<?php echo $block->getIdentifier(); ?>">
        <?php foreach($_countryCollection as $_country): ?>
            <li class="item">
                <span class="country-name"><?php echo $_country->getName() ?></span>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
