<?php /** @var $block \Netbaseteam\Calculatorshipping\Block\Product\Renderer\Configurable */ ?>
<link rel="stylesheet" type="text/css" href="<?php /* @escapeNotVerified */ echo $block->getViewFileUrl('Magento_Swatches::css/swatches.css') ?>"/>

<div class="swatch-opt" data-role="swatch-options"></div>

<script type="text/javascript">
    require([
        'jquery',
        'mage/mage',
        'swatchRenderer01'
    ], function ($) {
        $('[data-role=swatch-options]').SwatchRenderer({
            "jsonConfig": <?php /* @escapeNotVerified */ echo $swatchOptions = $block->getJsonConfig(); ?>,
            "jsonSwatchConfig": <?php /* @escapeNotVerified */
                echo $swatchOptions = $block->getJsonSwatchConfig(); ?>,
            "selectorProduct": '#estshippingcost_content_option_product',
            "mediaCallback": "<?php /* @escapeNotVerified */ echo $block->getMediaCallback() ?>",
            "onlyMainImg": <?php /* @escapeNotVerified */ echo $block->getVar('change_only_base_image',
                'Magento_Swatches') ?: 'false'; ?>
        });
        
        $(document).ready(function() {
            $(".photo.image").after('<span class="btn-loading-image-wrapper"><input type="button" class="btn-loading-image" value="Loading..."></span>');
            $('.btn-loading-image-wrapper').hide();
        });
    });
</script>