<?php
/**
 * Blackbird ContentManager Module
 *
 * NOTICE OF LICENSE
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@bird.eu so we can send you a copy immediately.
 *
 * @category        Blackbird
 * @package         Blackbird_ContentManager
 * @copyright       Copyright (c) 2017 Blackbird (https://black.bird.eu)
 * @author          Blackbird Team
 * @license         https://www.advancedcontentmanager.com/license/
 */
?>
<?php /** @see \Blackbird\ContentManager\Block\Content\Widget\ContentList */ ?>
<?php
    $collection = $block->getCollection();
    $link = $block->getLink();
?>
<div class="block widget contenttype-listing contents-grid grid">
    <?php if (!empty($block->getTitle())) : ?>
    <div class="block-title">
        <strong><?= $block->getTitle() ?></strong>
    </div>
    <?php endif; ?>
    <div class="block-content">
        <?php if ($collection->count()) : ?>
            <?php if ($block->hasPagerTop()) : ?>
                <div class="toolbar-bottom">
                    <div class="toolbar top">
                        <?= $block->getPagerHtml(); ?>
                    </div>
                </div>
            <?php endif; ?>

            <div class="contents-items widget-content-grid">
                <?php foreach ($collection as $content) : ?>
                    <div class="content-item">
                        <?php // Has Link Top ?>
                        <?php if ($block->hasLinkTop()) : ?>
                            <a class="contenttype-listing-readmore" href="<?php echo $content->getLinkUrl(); ?>"><?php echo __($link['label']); ?></a>
                        <?php endif; ?>

                        <?php if (count($block->getAttributeToShow()) == 0) : ?>
                            <?php echo $content->render('title', ['has_link' => true]); ?>
                        <?php else: ?>
                            <?php foreach ($block->getAttributeToShow() as $attribute) : ?>
                                <?php echo $content->render($attribute['attribute'], $attribute['params']); ?>
                            <?php endforeach; ?>
                        <?php endif; ?>

                        <?php // Has Link Bottom ?>
                        <?php if ($block->hasLinkBottom()) : ?>
                            <a class="contenttype-listing-readmore" href="<?php echo $content->getLinkUrl(); ?>"><?php echo __($link['label']); ?></a>
                        <?php endif; ?>
                    </div>
                <?php endforeach; ?>
            </div>

            <div style="clear: both"></div>

            <?php if ($block->hasPagerBottom()) : ?>
                <div class="toolbar-bottom">
                    <div class="toolbar bottom">
                        <?php echo $block->getPagerHtml(); ?>
                    </div>
                </div>
            <?php endif; ?>

        <?php else: ?>
            <div class="message info empty">
                <span><?= __('We can\'t find contents matching the selection.') ?></span>
            </div>
        <?php endif; ?>
    </div>
</div>
