<?php

?>
<div class="order-payment-method-name"><?php echo $block->escapeHtml($block->getMethod()->getTitle()); ?></div>
<table class="data-table admin__table-secondary">
    <tr>
        <th><?php echo $block->escapeHtml(__('Bank Account Number')); ?>:</th>
        <td><?php echo $block->escapeHtml(str_pad(substr($block->getInfo()->getAdditionalInformation()['bank_account_number'],-4), 14, 'X', STR_PAD_LEFT)); ?></td>
    </tr>
</table>
